### ISSUE TITLE
Restoring error asr

### ISSUE THREAD

**Issue by colbygamer** [libimobiledevice/idevicerestore#104]
recv(12, 4) failed: connection closed
unable to read message size: -1
could not receive message
recv(12, 4) failed: connection closed
unable to read message size: -1
could not receive message
Initialized /dev/rdisk0s1s1 as a 2 GB case-sensitive HFS Plus volume
entering ramrod_probe_media
device partitioning scheme is GPT
find_filesystem_partitions: storage=/dev/disk0s1 system=/dev/disk0s1s1 data=/dev
/disk0s1s2 baseband data= log=
entering mount_partition
executing /sbin/fsck_hfs
journal_replay(/dev/disk0s1s1) returned 0
** /dev/rdisk0s1s1
        Cache size should be multiple of cache block size (currently 32K)
        Using cacheBlockSize=32K cacheTotalBlock=2011 cacheSize=64352K.
   Executing fsck_hfs (version hfs-305.10.1).
** Checking non-journaled HFS Plus Volume.
** Detected a case-sensitive volume.
   The volume name is System
** Checking extents overflow file.
** Checking catalog file.
** Checking multi-linked files.
** Checking catalog hierarchy.
** Checking extended attributes file.
** Checking volume bitmap.
** Checking volume information.
** Trimming unused blocks.
** The volume System appears to be OK.
        CheckHFS returned 0, fsmodified = 0
executing /sbin/mount_hfs
/dev/disk0s1s1 mounted on /mnt1
System mounted read-only
AMSupportPlatformCreateBufferFromNativeFilePath: open failed: No such file or di
rectory
__getFDRSealingMap_block_invoke: Could not load sealing map from '/usr/lib/FDRSe
alingMap.plist'
AMFDRSealingMapGetEntriesForDevice: Could not load sealing map
restored_fdr_initialize returned false
RestoredFDRCreate() returned 0
FDR is not supported on this device
RestoredFDRSaveData: restoredFDR is NULL, not able to preserve FDR data.
RestoredFDRSaveData success
entering check_for_restore_log
restore log does not exist
executing /sbin/fsck_hfs
journal_replay(/dev/disk0s1s2) returned 0
** /dev/rdisk0s1s2
        Cache size should be multiple of cache block size (currently 32K)
        Using cacheBlockSize=32K cacheTotalBlock=2011 cacheSize=64352K.
   Executing fsck_hfs (version hfs-305.10.1).
** Checking Journaled HFS Plus volume.
** Detected a case-sensitive volume.
   The volume name is Data
** Checking extents overflow file.
** Checking catalog file.
** Checking multi-linked files.
** Checking catalog hierarchy.
** Checking extended attributes file.
** Checking volume bitmap.
** Checking volume information.
** Trimming unused blocks.
** The volume Data appears to be OK.
        CheckHFS returned 0, fsmodified = 0
executing /sbin/mount_hfs
mount_hfs: Could not exec re-keying daemon /usr/libexec/rolld: No such file or d
irectory
/dev/disk0s1s2 mounted on /mnt2
entering dump_panic_logs
executing /System/Library/CoreServices/DumpPanic
entering check_for_ota_logs_with_mount_point
OTA logs will be preserved through the erase install
restore log does not exist
skipping log submission, failed to read user settings from: /mnt2/mobile/Library
/ConfigurationProfiles/EffectiveUserSettings.plist
Diagnostic log submission disabled
Searching /mnt2/mobile/Library/Logs/CrashReporter/
check_for_ota_logs_with_mount_point complete
Successfully checked for OTA logs
executing /sbin/fsck_hfs
journal_replay(/dev/disk0s1s2) returned 0
** /dev/rdisk0s1s2
        Cache size should be multiple of cache block size (currently 32K)
        Using cacheBlockSize=32K cacheTotalBlock=2011 cacheSize=64352K.
   Executing fsck_hfs (version hfs-305.10.1).
** Checking Journaled HFS Plus volume.
** Detected a case-sensitive volume.
   The volume name is Data
** Checking extents overflow file.
** Checking catalog file.
** Checking multi-linked files.
** Checking catalog hierarchy.
** Checking extended attributes file.
** Checking volume bitmap.
** Checking volume information.
** Trimming unused blocks.
** The volume Data appears to be OK.
        CheckHFS returned 0, fsmodified = 0
executing /sbin/mount_hfs
mount_hfs: Could not exec re-keying daemon /usr/libexec/rolld: No such file or d
irectory
/dev/disk0s1s2 mounted on /mnt2
AMSupportHttpCopyProxySettings: failed to register for reverse proxy availabilit
y
proxySettings is NULL
entering unmount_filesystems
entering unmount_partition
System unmounted
entering unmount_partition
Data not mounted (unmount ignored)
entering clean_NAND
NAND format complete
entering ramrod_probe_media
find_filesystem_partitions: storage=/dev/disk0 system= data= baseband data= log=

entering format_effaceable_storage
effaceable storage is formatted, clearing it
effaceable storaged cleared
entering format_storage_for_LwVM
entering ramrod_probe_media
device partitioning scheme is GPT
unexpected partition 'LwVM' - skipping
find_filesystem_partitions: storage=/dev/disk0s1 system= data= baseband data= lo
g=
entering create_filesystem_partitions
User specified system partition size, skipping firmware extras size.
system partition padding size is: 167772160 bytes
unable to open : No such file or directory
creating 2 partitions
creating encrypted data partition
entering ramrod_probe_media
device partitioning scheme is GPT
find_filesystem_partitions: storage=/dev/disk0s1 system=/dev/disk0s1s1 data=/dev
/disk0s1s2 baseband data= log=
wipe entire partition: 1 (old = 0 new = 1979)
block size for /dev/disk0s1s1: 8192
/sbin/newfs_hfs -s -v System -J -b 8192 -n a=8192,c=8192,e=8192 /dev/disk0s1s1
executing /sbin/newfs_hfs -s -v System -J -b 8192 -n a=8192,c=8192,e=8192 /dev/d
isk0s1s1
Initialized /dev/rdisk0s1s1 as a 2 GB case-sensitive HFS Plus volume with a 8192
k journal
block size for /dev/disk0s1s2: 8192
/sbin/newfs_hfs -s -v Data -J -P -b 8192 -n a=8192,c=8192,e=8192 /dev/disk0s1s2

executing /sbin/newfs_hfs -s -v Data -J -P -b 8192 -n a=8192,c=8192,e=8192 /dev/
disk0s1s2
Initialized /dev/rdisk0s1s2 as a 13 GB case-sensitive HFS Plus volume with a 819
2k journal
entering ramrod_probe_media
device partitioning scheme is GPT
find_filesystem_partitions: storage=/dev/disk0s1 system=/dev/disk0s1s1 data=/dev
/disk0s1s2 baseband data= log=
entering mount_filesystems
entering mount_partition
executing /sbin/fsck_hfs
journal_replay(/dev/disk0s1s1) returned 0
** /dev/rdisk0s1s1
        Cache size should be multiple of cache block size (currently 32K)
        Using cacheBlockSize=32K cacheTotalBlock=2011 cacheSize=64352K.
   Executing fsck_hfs (version hfs-305.10.1).
** Checking Journaled HFS Plus volume.
** Detected a case-sensitive volume.
   The volume name is System
** Checking extents overflow file.
** Checking catalog file.
** Checking multi-linked files.
** Checking catalog hierarchy.
** Checking extended attributes file.
** Checking volume bitmap.
** Checking volume information.
** Trimming unused blocks.
** The volume System appears to be OK.
        CheckHFS returned 0, fsmodified = 0
executing /sbin/mount_hfs
/dev/disk0s1s1 mounted on /mnt1
System mounted read-write
entering mount_partition
executing /sbin/fsck_hfs
journal_replay(/dev/disk0s1s2) returned 0
** /dev/rdisk0s1s2
        Cache size should be multiple of cache block size (currently 32K)
        Using cacheBlockSize=32K cacheTotalBlock=2011 cacheSize=64352K.
   Executing fsck_hfs (version hfs-305.10.1).
** Checking Journaled HFS Plus volume.
** Detected a case-sensitive volume.
   The volume name is Data
** Checking extents overflow file.
** Checking catalog file.
** Checking multi-linked files.
** Checking catalog hierarchy.
** Checking extended attributes file.
** Checking volume bitmap.
** Checking volume information.
** Trimming unused blocks.
** The volume Data appears to be OK.
        CheckHFS returned 0, fsmodified = 0
executing /sbin/mount_hfs
mount_hfs: Could not exec re-keying daemon /usr/libexec/rolld: No such file or d
irectory
/dev/disk0s1s2 mounted on /mnt2
Data mounted read-write
entering resize_system_partition_to_options
entering unmount_filesystems
entering unmount_partition
System unmounted
entering unmount_partition
Data unmounted
entering restore_images
Successfully marked device node /dev/rdisk0s1s1 as static data
executing /usr/sbin/asr -source asr://localhost:12345 -target /dev/disk0s1s1 -er
ase -noprompt --chunkchecksum --puppetstrings
SYSLOG: Jun  2 11:02:25 localhost kernel[0] <Notice>: void AppleUSBDeviceMux::ha
ndleConnectResult(struct BulkUSBMuxSession *, errno_t) new session to port 12345
 failed: 61
SYSLOG: Jun  2 11:02:25 localhost asr[29] <Error>: bootstrap_look_up2 failed wit
h 0x44e
ASR: asr: Unable to disable idle sleep - -536870199
ASR STATUS: start       242.6   multicast-client
ASR: Waiting for connection attempt from server
SYSLOG: Jun  2 11:02:25 localhost asr[29] <Error>: __net_helper_get_connection_b
lock_invoke_3 could not connect to networkd
ASR STATUS: setup
ASR: Validating target...
ASR: done
ASR STATUS: metadata
ASR: Validating source...
ASR: done
ASR: Retrieving scan information...
ASR: done
ASR: Validating sizes...
ASR: done
ASR STATUS: restore
ASR RESTORE PROGRESS: 2%
ASR RESTORE PROGRESS: 4%
ASR RESTORE PROGRESS: 6%
ASR RESTORE PROGRESS: 8%
ASR RESTORE PROGRESS: 10%
ASR RESTORE PROGRESS: 12%
ASR RESTORE PROGRESS: 14%
ASR RESTORE PROGRESS: 16%
ASR RESTORE PROGRESS: 18%
ASR RESTORE PROGRESS: 20%
ASR RESTORE PROGRESS: 22%
ASR RESTORE PROGRESS: 24%
ASR RESTORE PROGRESS: 26%
ASR RESTORE PROGRESS: 28%
ASR RESTORE PROGRESS: 30%
ASR RESTORE PROGRESS: 32%
ASR RESTORE PROGRESS: 34%
ASR RESTORE PROGRESS: 36%
ASR RESTORE PROGRESS: 38%
ASR RESTORE PROGRESS: 40%
ASR RESTORE PROGRESS: 42%
ASR RESTORE PROGRESS: 44%
ASR RESTORE PROGRESS: 46%
ASR RESTORE PROGRESS: 48%
ASR RESTORE PROGRESS: 50%
ASR RESTORE PROGRESS: 52%
ASR RESTORE PROGRESS: 54%
ASR RESTORE PROGRESS: 56%
ASR RESTORE PROGRESS: 58%
ASR RESTORE PROGRESS: 60%
ASR RESTORE PROGRESS: 62%
ASR RESTORE PROGRESS: 64%
ASR RESTORE PROGRESS: 66%
ASR RESTORE PROGRESS: 68%
ASR RESTORE PROGRESS: 70%
ASR RESTORE PROGRESS: 72%
ASR RESTORE PROGRESS: 74%
ASR RESTORE PROGRESS: 76%
ASR RESTORE PROGRESS: 78%
ASR RESTORE PROGRESS: 80%
ASR RESTORE PROGRESS: 82%
ASR RESTORE PROGRESS: 84%
ASR RESTORE PROGRESS: 86%
ASR RESTORE PROGRESS: 88%
ASR RESTORE PROGRESS: 90%
ASR RESTORE PROGRESS: 92%
ASR RESTORE PROGRESS: 94%
ASR RESTORE PROGRESS: 96%
ASR RESTORE PROGRESS: 98%
ASR: asr: Image failed signature verification
ASR: asr: Failed to read the stream: Authentication error
ASR: __decompressChunk: backing store read at offset 1362758130 length 88679 fai
led with error 80
ASR: __decompressChunk() error: 80
ASR STATUS: fail
SYSLOG: Jun  2 11:05:54 localhost kernel[0] <Notice>: disk0s1s1: alignment error
.
ASR: newfs_hfs:
ASR: MarkExtentUsed::pread(3, 0x17895000, 8192, 4096): Invalid argument
ASR: /sbin/newfs_hfs failed with error 256
ASR: Could not restore - Authentication error
ASR STATUS: fail

ERROR: Unable to successfully restore device
ERROR: Unable to restore device                                                                                                                                                 

How do i fix this error?
Ipad 2,1 trying to restore to 9.3.1

**Comment by Sn0wDev** [comment]
erm, if 9.3.1 is still signed, i'm going to assume that your ipsw is corrupted. try redownloading, and if it still doesnt work, put the ipad into dfu or recovery before restoring.
that was what worked for me :D

**Comment by nikias** [comment]
This error happened to me when I tried to restore to iOS 10 beta. I committed a fix for that; @colbygamer can you try with the latest code from git?

**Comment by Sn0wDev** [comment]
hrmmm. strange. it happened when the ipsw seemed to be corrupt. i redownloaded, put my ipad into recovery, and the restore worked perfectly

**Comment by colbygamer** [comment]
@sn0wDew it's a custom firmware restore

**Comment by nikias** [comment]
@colbygamer custom firmwares don't work for the iPad 2. It only works for older generation devices iPhone 4 or below, iPad 1.
Closing this tickets since custom firmwares are not supported.
