### ISSUE TITLE
Failed restore iPhone6+ iOS9.3.2 and iOS 10 beta

### ISSUE THREAD

**Issue by RonnieLLL** [libimobiledevice/idevicerestore#107]

**Comment by nikias** [comment]
Can you try with latest code from git?

**Comment by Sum1n** [comment]
you can use this video to fix this problem restore idevice on kali linux using libmobiledevice
https://www.youtube.com/watch?v=qRin2ggBGjw

**Comment by 4kzeng** [comment]
I have a similar problem on iPhone5c,  restoring iOS 10, it works fine. but cannot downgrade 9.3.3.  Stuck in enter restore mode.

**Comment by nikias** [comment]
Downgrade won't work unless special circumstances are given. Check futurerestore for more information.
