### ISSUE TITLE
IDeviceRestore will not configure

### ISSUE THREAD

**Issue by ghost** [libimobiledevice/idevicerestore#115]
**System:** Ubuntu GNOME 16.04.1 LTS  
**Packages:** All dependencies required by libimobiledevice, libirecovery, idevicerestore, and ideviceactivate (installed libc6-dev in place of librt-dev, and libglib2.0-dev in place of libglib2-dev)  

**Problem:** IDeviceRestore halts at the `./autogen.sh` stage. Here is the relevant debug:

```
checking for libimobiledevice... no
configure: error: Package requirements (libimobiledevice-1.0 >= 1.1.6) were not met:
No package 'libimobiledevice-1.0' found
Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.
Alternatively, you may set the environment variables libimobiledevice_CFLAGS
and libimobiledevice_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

I have installed the `libimobiledevice6` package, and installed `libirecovery` from source, but the `./configure` script wants `libimobiledevice-1.0`, and not `libimobiledevice6`. 

**How can I get it to configure with my current version of libimobiledevice?**

**Comment by nikias** [comment]
You need to install libimobiledevice-devel but that version is outdated. Compile and install latest libimobiledevice and all dependencies from source.
