### ISSUE TITLE
Cannot restore iphone 5s to iOS 10 in Ubuntu

### ISSUE THREAD

**Issue by walkman4321** [libimobiledevice/idevicerestore#123]
I cannot restore iphone 5s to iOS 10 in ubuntu using idevicerestore .So i follow every instruction mention in "https://github.com/libimobiledevice/idevicerestore/issues/89" .Still It can't restore firmware to my Iphone 5s. When i again debug code i found that it cannot write data to ".dmg" file .Please help me to figure out this problem

**Comment by nikias** [comment]
Can you post the output of the idevicerestore command you are using, with -d ?
