### ISSUE TITLE
fdr 0362C908

### ISSUE THREAD

**Issue by kitukie** [libimobiledevice/idevicerestore#126]
FDR 0362C908 timeout waiting for command
FDR 0362C908 terminating...
ERROR: Unable to restore device

-
i try couple time to restore iphone 6 with cfw ios 10.0.2  but find some problem, hope anyone can help
thank

**Comment by nikias** [comment]
People, come on! A custom firmware does not work for averything newer than the iPhone 4! Don't believe that fce355/iDeviceCentral crap!
