### ISSUE TITLE
ERROR: Could not connect to lockdownd, error code -5

### ISSUE THREAD

**Issue by walkman4321** [libimobiledevice/idevicerestore#142]
I am running following command on terminal to get information of IOS device  in Ubuntu 14.04
       >" sudo ideviceinfo"

& I'm getting following output
     ERROR: Could not connect to lockdownd, error code -5
And also press trust button in IOS device ,still I'm getting same output 
Please help me!!!!

**Comment by nikias** [comment]
You need to update all libraries from source. The prebuilt packages from ubuntu are outdated.
