### ISSUE TITLE
core dump..

### ISSUE THREAD

**Issue by nicnic2001** [libimobiledevice/idevicerestore#144]
http://pastebin.com/yuG315iR

take a look at my log^

any help appreciated!

Nick

**Comment by xnuos** [comment]
I have the same issue. Trying to use tihmstar's futurerestore but this is halting the compiling of the program (at least for me on linux)

**Comment by nikias** [comment]
This was a problem with libimobiledevice and newer version of openssl. Updating to latest libimobiledevice (compiled from source) should resolve the issue.
