### ISSUE TITLE
ERROR: Unable to restore device

### ISSUE THREAD

**Issue by dimple09cruz** [libimobiledevice/idevicerestore#145]
C:\libi>idevicerestore.exe -u --9147090b03e8f0888e74676c6a23eacd8c857ea26b7824c06563dbc1e9040857aa2e8253 -c iPhone4,1_7.1.2_11D257_Restore.ipsw
NOTE: using cached version data
Found device in Normal mode
Identified device as iPhone4,1
Extracting Restore.plist from IPSW
Product Version: 7.1.2
Product Build: 11D257 Major: 11
Device supports Image4: false
Custom firmware requested. Disabled TSS request.
Variant: Customer Upgrade Install (IPSW)
This restore will update your device without losing data.
Using cached filesystem from 'iPhone4,1_7.1.2_11D257_Restore/058-4365-009.dmg'
Entering recovery mode...
INFO: device serial number is C28JV3UKDTD1
Extracting iBEC.n94ap.RELEASE.dfu...
Not personalizing component iBEC...
Sending iBEC (278924 bytes)...
Getting ApNonce in recovery mode... d4 3a 08 39 61 39 5e f4 06 9a e9 a1 cc 97 31 b4 51 30 71 87
Recovery Mode Environment:
iBoot build-version=iBoot-2817.60.2
iBoot build-style=RELEASE
Sending AppleLogo...
Extracting applelogo@2x~iphone.s5l8940x.img3...
Not personalizing component AppleLogo...
Sending AppleLogo (6796 bytes)...
Extracting 058-4442-009.dmg...
Not personalizing component RestoreRamDisk...
Sending RestoreRamDisk (9584908 bytes)...
Extracting DeviceTree.n94ap.img3...
Not personalizing component RestoreDeviceTree...
Sending RestoreDeviceTree (81164 bytes)...
Extracting kernelcache.release.n94...
Not personalizing component RestoreKernelCache...
Sending RestoreKernelCache (8435788 bytes)...
About to restore device...
Waiting for device...
ERROR: Unable to connect to device in restore mode
ERROR: Unable to open device in restore mode
ERROR: Unable to restore device

**Comment by nikias** [comment]
You can't restore custom firmware on the iPhone 4s.
