### ISSUE TITLE
Error when compiling the new version of idevicerestore with mingw32

### ISSUE THREAD

**Issue by iFred09** [libimobiledevice/idevicerestore#151]
Hello,

I use mingw32 to build idevicerestore.
In the old version I can build without problem. The new version don't work, idevicerestore said me a error when I try to compile the tool.

Can you fix it ? 
![sans titre](https://cloud.githubusercontent.com/assets/22419166/23272383/5d235916-f9fb-11e6-9400-306743aa2692.png)

**Comment by nikias** [comment]
Yes. I will push out a fix.

**Comment by iFred09** [comment]
Perfect.

**Comment by nikias** [comment]
Fixed with commit aa908d392de533d693dae9883f61a3d7b26cfd4d.
