### ISSUE TITLE
Make idevicerestore error

### ISSUE THREAD

**Issue by tolikes** [libimobiledevice/idevicerestore#152]
ipsw.c:28:10: fatal error: 'openssl/sha.h' file not found
#include <openssl/sha.h>
         ^
1 error generated.
make[2]: *** [idevicerestore-ipsw.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by braden-wright93** [comment]
Do you have OpenSSL installed?
A lot of the options included here related to sha1 sums seem to be deprecated, but it still compiles/runs.

**Comment by nikias** [comment]
Not a bug. Install openssl development packages.
