### ISSUE TITLE
Restore iPhone 6 failed, drop in DFU mode !

### ISSUE THREAD

**Issue by truonggiang0710** [libimobiledevice/idevicerestore#154]
Hi guys,
I have an issue with restoring on iPhone 6. iOS 10.3.
I try with last version. The logfile show finished, the result passed but my phone stuck at DFU mode.
I saw status bar in phone full and then my phone stuck...
I don't know why ! Please help me resolve this issue !
Thanks a lot

**Comment by nikias** [comment]
Is it really DFU mode, i.e. black screen? Or does it show the connect to iTunes screen, which is recovery mode? If so, can you kick the device out of recovery mode with irecovery tool?
```
irecovery -s
```
(wait for it to connect)
```
setenv auto-boot true
saveenv
reboot
```
Press ctrl+c to exit.

**Comment by truonggiang0710** [comment]
Yes, It really in DFU mode. It's in black screen.

**Comment by applebeast** [comment]
Ok. 2 things to do. 

First, hold the home and power buttons down at the same time for 15 seconds, then wait 5 seconds and hit the power. If this doesn't work, you need to do 1 of 3 things: open the phone and dis/reconnect thd battery, or finally just put it in the freezer until the battery's chemical reactions stop, and then take it out and turn it on.

**Comment by applebeast** [comment]
restore it again.

**Comment by nikias** [comment]
Does it restore with iTunes?

**Comment by truonggiang0710** [comment]
It's restored OK over iTunes !

**Comment by nikias** [comment]
No idea then... if you have the option to restore the device again with idevicerestore we can have a closer look. If not we can close the issue.
