### ISSUE TITLE
libimobiledevice-win32/idevicerestore Win32 

### ISSUE THREAD

**Issue by vipinbeni** [libimobiledevice/idevicerestore#161]
![1](https://cloud.githubusercontent.com/assets/5228833/25033442/3ff9126e-20fb-11e7-9e4c-0ab6f06c84a9.jpg)
Hi Sir,
when i run this tool with VS2015 i got a Exception/crash  on the line ftello(f)

**Function Name**
int download_to_file(const char* url, const char* filename, int enable_progress)
**Line**
curl_easy_perform is return 23 errro and 
off_t sz = ftello(f);  // here my application closed 

it also show SSl_Read in stack  of crash data .

Kindly Help me Sir @nikias @FunkyM @posixninja @aburgh @boxingsquirrel

**Comment by nikias** [comment]
No support for Visual Studio related issues.
