### ISSUE TITLE
Impossible to install CFW on ios 10.3.1

### ISSUE THREAD

**Issue by mathius1714** [libimobiledevice/idevicerestore#167]
Hello, I'm trying to install a Custom IPSW with the "setup.app" already patched to do an Icloud Bypass  Iphone 6. I got many times "Error: 14" on iTunes, so now I'm trying to install with libimobiledevices, this is my error:

C:\Libi>idevicerestore.exe -u --2c3ac7bbcf63d0ca62120867cbef51d0c427c231 -c iPhone_4.7_10.3.1_14E304_Restore.ipsw
NOTE: Updated version data.
Found device in Recovery mode Identified device as n61ap, iPhone7,2
Extracting Restore.plist from IPSW
Product Version: 10.3.1
Product Build: 14E304 Major: 14
INFO: device serial number is -----------
Device supports Image4: true
Custom firmware requested. Disabled TSS request.
ERROR: zip_name_locate: Firmware/all_flash/all_flash.n61ap.production/manifest
ERROR: could not extract Firmware/all_flash/all_flash.n61ap.production/manifest from IPSW

I'm noob programming and I'm using Windows  but I've Osx too. I need help!

Thank you so much!

**Comment by nikias** [comment]
PLEASE PLEASE UNDERSTAND THIS:
Custom Firmwares **DO NOT WORK** WITH ANY NEWER DEVICE. Newer means newer than iPhone 4.
FCE 365 / iDeviceCentral is spreading false information and makes USELESS FAKE VIDEOS. Not only that custom firmwares can't be restored but also the steps shown do not make any sense whatsoever. Complete bullshit!
Good as comedy though if you're from the scene.
