### ISSUE TITLE
Unable to restore iPhone 6 and iPhone 6 Plus (A8)

### ISSUE THREAD

**Issue by mpenttil** [libimobiledevice/idevicerestore#17]
Noticed the latest updates regarding iPhone6 support and decided to try upgrading 8.1 to iPhone 6 with idevicerestore. After toying a bit with tss.c: 

diff --git a/src/tss.c b/src/tss.c
index 99c4538..1ff27c2 100644
--- a/src/tss.c
+++ b/src/tss.c
@@ -481,7 +481,9 @@ int tss_request_add_ap_tags(plist_t request, plist_t parameters, plist_t overrid
                }
 
                /* FIXME: only used with diagnostics firmware */
-               if ((strcmp(key, "Diags") == 0) || (strcmp(key, "OS") == 0)) {
+               if ((strcmp(key, "Diags") == 0) || (strcmp(key, "OS") == 0) ||
+                   (strcmp(key, "rfta") == 0) || (strcmp(key, "rfts") == 0) ||
+                   (strcmp(key, "ftap") == 0) || (strcmp(key, "ftsp") == 0)) {
                        free(key);
                        continue;
                }

I can download shsh-blobs from Apple, but idevicerestore process terminates with:

...
Done sending RootTicket
Partition NAND device (28)
...
Unknown data request 'FDRTrustData' received
No data to read
No data to read
...

I assume there are additional steps required by restored to flash iPhone6, any plan to have these added?

**Comment by shine911** [comment]
i have same problem how can fix it :( ?

**Comment by id3283** [comment]
Hi, were these changes eventually integrated into the trunk?

**Comment by jalcock0** [comment]
Hi Guys,

I am running into this error when attempting to restore iPhone 6 and 6 Plus. FDR related.

I have added the logs here:

DWLOG /devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.2/1-1.2.2: _AMFDRHttpMessageSendSync: URL connection error occurred: Error Domain=NSURLErrorDomain Code=-1009 "The Internet connection appears to be offline." UserInfo=0x15561d4f0 {NSUnderlyingError=0x155614fa0 "The Internet connection appears to be offline.", NSErrorFailingURLStringKey=http://gg.apple.com/fdrtrustobject/5340B6A059BDB732E715E7BB1B292EDCD45C2A8D1D07E6039D3F338D7C4428AB, NSErrorFailingURLKey=http://gg.apple.com/fdrtrustobject/5340B6A059BDB732E715E7BB1B292EDCD45C2A8D1D07E6039D3F338D7C4428AB, _kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=57, NSLocalizedDescription=The Internet connection appears to be offline.}#015
DWLOG /devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.2/1-1.2.2: _AMFDRHttpMessageSendSync: HTTP request failed, httpResponseHeader is NULL#015
DWLOG /devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.2/1-1.2.2: _AMFDRHttpMessageSendSync: HTTP server returned unexpected FDR response code -1#015
DWLOG /devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.2/1-1.2.2: _AMFDRHttpMessageSendSync: !!!!!!!!!!!!!!!!!!!!!!!!!! Retries exhausted on attempt 3 !!!!!!!!!!!!!!!!!!!!!!!!!!#015
DWLOG /devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.2/1-1.2.2: AMFDRCreateError: _AMFDRHttpRequestSendSyncNoRetry: _AMFDRHttpMessageSendSync failed: code=8#015
DWLOG /devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.2/1-1.2.2: AMFDRCreateError: _AMFDRHttpRequestSendSync: httpResponseHeader is NULL: code=10#015
DWLOG /devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.2/1-1.2.2: AMFDRCreateError: AMFDRDataHTTPCopyTrustObject: AMFDRDataHTTPCopyTrustObject failed: code=8#015
DWLOG /devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.2/1-1.2.2: -[AMSupportUERROR: Unable to successfully restore device#015
DWLOG /devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.2/1-1.2.2: ERROR: Unable to restore device#015
DWLOG /devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.2/1-1.2.2: RLConnectionDelegate dealloc]: dealloc-ing delegate#015
DWLOG /devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.2/1-1.2.2: failed to copy trust object from fdrHttp#015
DWLOG /devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.2/1-1.2.2: 0: AMFDRError/8: AMFDRDataHTTPCopyTrustObject failed#015
DWLOG /devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.2/1-1.2.2: 1: AMFDRError/a: httpResponseHeader is NULL#015
DWLOG /devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.2/1-1.2.2: 2: AMFDRError/8: _AMFDRHttpMessageSendSync failed#015
DWLOG /devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.2/1-1.2.2: RestoredFDRCreate() returned 6#015
DWLOG /devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.2/1-1.2.2: FDR is not supported on this device#015
DWLOG /devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.2/1-1.2.2: #015
DWLOG /devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.2/1-1.2.2: Semaphore completed and bus number is 1#015
DWLOG /devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.2/1-1.2.2: idevicerestore exited with status 250#015

Can anyone shed any light on this issue?

Thanks, John.

**Comment by neilbrownlee** [comment]
Hi All,

Any chance we can commit the changes? I see they have been waiting for a short while.

**Comment by FunkyM** [comment]
Fixed as changes are not in git master head.

**Comment by julian2706** [comment]
hola me podrian Ayudar yo tengo mi iphone 5s y vi Este Mensaje y el mio quedo FUE BUENO DIGAMOS QUE ASI Q SOLO 6,1 BLA, BLA Descargue EL DEL IPHONE 5S GSM Q ES EL MIO 
Dispositivo Que SE Encuentra en el Modo normal 
Dispositivo IDENTIFICADO Como iPhone7,1 
Extracción de BuildManifest IPSW 
Versión del producto: 8.4.1 
Build producto: 12H321 alcalde: 12 
Dispositivo apoya Image4: Verdadera 
variation de borrado Cliente Instalar (IPSW) 
Este Restaurar borrará los Datos del Dispositivo. 
Encontrado ECID ##### ########### 
CONSEGUIR ApNonce en Modo normal de 58 ... 55 7c 1a e8 4b 9d 43 96 89 16 e3 D2 D1 f2 6e 89 E7 A7 B7 
al buscar El Nuevo SHSH blob 
CONSEGUIR SepNonce en Modo normal, ... 6e 64 2d d4 f5 df 9e af 5e 41 d8 01 66 c8 f2 c2 e6 4c c4 1d
URL de Solicitud establecido en https://gs.apple.com/TSS/controller?action=2
Envío de Solicitud de Intento de TSS 1 ... Respuesta con Éxito recibidas 
recibidas SHSH 
Extracción del Sistema de Archivos IPSW 
de entrar en Modo de Recuperación ... 
INFO: Número de Serie del Dispositivo es ############ 
Extracción iBEC. n56.RELEASE.im4p ... 
Envío de iBEC (648713 bytes) ... 
el Modo de Recuperación para el Medio Ambiente: 
iBoot Construir-version = iBoot-2261.30.37 
iBoot Construir-style = LIBERACIÓN 
Enviando AppleLogo ... 
La Extracción de applelogo@3x~iphone.t7000.im4p ... 
Envío de AppleLogo (18859 bytes) ... 
del disco RAM-size = 0x4000000 
La Extracción 058-23799-023.dmg ... 
Enviando RestoreRamDisk (17495549 bytes) ... 
La Extracción de DeviceTree.n56ap.im4p ... 
Enviando RestoreDeviceTree (168375 bytes). .. 
La Extracción kernelcache.release.n56 ... 
Envío de RestoreKernelCache (9462180 bytes) ... 
Acerca de Restaurar el Dispositivo ... 
Esperando ... Dispositivo 
El Dispositivo this Ahora Conectado en Modo de Restauración ... 
Conexión de Ahora ... 
Conectado una com.apple.mobile.restored, la versión 13 
del Dispositivo ha entrado con Éxito en Restaurar el Modo de 
Información de hardware: 
BoardID: 4 
ChipID: 28672 
UniqueChipID: ########### ### 
ProductionMode: Verdadera 
FDRSupport Indicado, un oyente partir FDR Hilo 
a punto de enviar NORData ... 
Ruta del firmware Encontrado firmware / all_flash / all_flash.n56ap.production 
obtencion de firmware Manifiesta firmware / all_flash / all_flash.n56ap.production / Manifiesta 
Que extrae LLB.n56.RELEASE.im4p ... 
La Extracción de DeviceTree.n56ap. im4p ... 
La Extracción de applelogo@3x~iphone.t7000.im4p ... 
La Extracción de batterycharging0@3x~iphone.t7000.im4p ... 
La Extracción de batterycharging1@3x~iphone.t7000.im4p ... 
La Extracción de batteryfull @ 3x ~ iPhone. t7000.im4p ... 
La Extracción de batterylow0@3x~iphone.t7000.im4p ... 
La Extracción de batterylow1@3x~iphone.t7000.im4p ... 
La Extracción de glyphplugin@1920~iphone-lightning.t7000.im4p ... 
La Extracción de iBoot. n56.RELEASE.im4p ... 
La Extracción de recoverymode@1920~iphone-lightning.t7000.im4p ... 
La Extracción Sep-firmware.n56.RELEASE.im4p ... 
La Extracción Sep-firmware.n56.RELEASE.im4p ... 
Enviando NORData Ahora ... 
Realiza Enviando NORData 
punto de enviar RootTicket ... 
Envío de RootTicket Ahora ... 
Hecho enviar RootTicket 
Dispositivo de reparto NAND (28) 
QUEDA AY NO SE, MIRO EL IPHONE Y Aparece la Manzana CON BARRA PERO NI CARGA, Y CUANDO LO DESCONECTO Aparece la Manzana UNOS 20 O MAS SEGUNDOS Y PANTALLA AZUL Y SE DE NUEVO Y LO RESTAURO CON ITUNES PERO PUES QUIERO RESTAURARLO DEL TODO, quiciera SABER CUANTO TIEMPO SE DEMORA PARA QUE avanze DEL (28) FAVOR POR diganme Al menos CUANTO ESPERO GRACIAS POR FAVOR ESCRIBIRME A ESTE GMAIL juliangon.2000@gmail.com
