### ISSUE TITLE
iPhone 4s stuck in recovery after "idevicerestore.exe -e custom.ipsw"

### ISSUE THREAD

**Issue by olivur8** [libimobiledevice/idevicerestore#179]
Jailbroke my 4s on 9.3.5, and tried downgrading to 6.1.3 using [https://www.reddit.com/r/jailbreak/comments/5lakuy/tutorial_easy_downgrade_for_iphone_4s_from_933_to/](this) tutorial. idevicerestore stopped recognizing my phone:

>ERROR: Unable to connect to device in restore mode
>ERROR: Unable to open device in restore mode
>ERROR: Unable to restore device.   

Now it's stuck in recovery mode, and iTunes can't restore it (error 4013).

**Comment by d3vCr0w** [comment]
Did you replace the battery on your device?

**Comment by olivur8** [comment]
Was able to fix this using 3uTools ”flasher”.
