### ISSUE TITLE
Restore fails on IPSW files >2GB on 32bit arch

### ISSUE THREAD

**Issue by FunkyM** [libimobiledevice/idevicerestore#18]
This is a bug in libzip where LFS support is broken for 32bit architectures due to the wrong order of includes.
There is a patch for it here but this needs a fix upstream:
https://build.opensuse.org/package/view_file/home:FunkyM:branches:devel:libraries:c_c++/libzip/libzip-fix-large-file-support.patch?expand=1

**Comment by FunkyM** [comment]
Fixed [upstream](http://hg.nih.at/libzip/rev/0cbad4ce07a7) now.

**Comment by vipinbeni** [comment]
Hi Sir @FunkyM ,
I also having the same problem.So i follow every instruction in above post.Still It can't restore firmware to my Iphone 5s. When i debug code i found that it cannot validate ASR my function fail in below calling in validation.

device_error = idevice_connection_receive(asr->connection, buffer, ASR_BUFFER_SIZE, &size);
    if (device_error != IDEVICE_E_SUCCESS) {
        **error("ERROR: Unable to receive data from ASR\n");**
        free(buffer);
        return -1;
    }

while (1) {
        if (asr_receive(asr, &packet) < 0) {
            **error("ERROR: Unable to receive validation packet\n");**
            return -1;
        }

dear sir kindly help me as it work fine on ipsw less then 2 gb but fail on ipsw 2.2 gb fir 5S ios 10.2

**Comment by vipinbeni** [comment]
@nikias  i have already  make changes to asr file and ipsw file according to this and also  _feeski64 is not working on ubantu so i have used fseeko64 but it return wrong length of 2.2 gb file . while the same is doing fine with 4s update with less then 2 gb file on ubantu 14.4 32bit os. kindly help me ..
