### ISSUE TITLE
Unknown data request 'DeviceTree' received

### ISSUE THREAD

**Issue by deiiviid96** [libimobiledevice/idevicerestore#191]
iPad Air 2 11.0.3 IOS

Error message:

Installing kernelcache (27)
Unknown data request 'DeviceTree' received
common.c:printing 291 bytes plist:
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>DataType</key>
        <string>DeviceTree</string>
        <key>MsgType</key>
        <string>DataRequestMsg</string>
</dict>
</plist>
No data to read
FDR 0000000003ADCE90 timeout waiting for command
FDR 0000000003ADCE90 waiting for message...
No data to read
No data to read
FDR 0000000003ADCE90 timeout waiting for command
FDR 0000000003ADCE90 waiting for message...
No data to read
No data to read

it stays in loop:

FDR 0000000003ADCE90 timeout waiting for command
FDR 0000000003ADCE90 waiting for message...
No data to read
No data to read

Maybe I don't have the latets code. Can anyone give me the latest code compiled? Thank you!

**Comment by nikias** [comment]
This was fixed with commit https://github.com/libimobiledevice/idevicerestore/commit/b99782b2f4466270dbea0f87757df30e7b835084.
