### ISSUE TITLE
Can't restore Iphone SE (Unable to discover device type)

### ISSUE THREAD

**Issue by AWDangel** [libimobiledevice/idevicerestore#194]
I have an Iphone SE actually with ios 10.3.3 and im trying to upgrade it to ios 11, but i simply cant go through this step, only pops:

Reading data from version.xml
NOTE: using cached version data
Found device in Normal mode
ERROR: Unable to discover device type

Please some help! i would really apreciate it

**Comment by Dantee296** [comment]
@AWDangel you are using old libirecovery
make sure u have latest source code
also try to delete the version.xml and let it create the new one

**Comment by nikias** [comment]
@AWDangel as @Dantee296 is pointing out you need to use a more recent libirecovery.
