### ISSUE TITLE
Question| can i upgrade iphone se from ios 9.3.2 to 9.3.3 or 10.x.x

### ISSUE THREAD

**Issue by B4RD4k** [libimobiledevice/idevicerestore#195]
Hi,
I have iphone SE 9.3.2 jailbroken and i want to upgrade my device to a more stable firmware such as 9.3.3 - 10.x.x for a better jailbreak (unathetre).

It is possible?

10x

**Comment by nikias** [comment]
As you can see here:
https://ipsw.me/iPhone8,4
The latest firmware Apple is still signing is 11.0.1 so the answer to your question is NO.
