### ISSUE TITLE
iPhone 4s stuck in Recovery Mode whilst restoring custom firmware (iOS 7.1.2)

### ISSUE THREAD

**Issue by krzysztofkaminski** [libimobiledevice/idevicerestore#20]
Hello,

I was trying to restore my iPhone 4s to iOS 7.1.2 (from 8.1) using idevicerestore and my device stuck in recovery mode.

While I am running idevicerestore it stuck on "Waiting for device..." as you can se in log below.
After timeout I got errors: 
ERROR: Unable to connect to device in restore mode
ERROR: Unable to open device in restore mode
ERROR: Unable to restore device

How can I bring iPhone to Normal Mode ?
I run Ubuntu 14.10.

sudo ./idevicerestore -c  iPhone4,1_7.1.2_11D257_Restore.ipsw 
NOTE: using cached version data
Found device in Recovery mode
Identified device as iPhone4,1
Extracting Restore.plist from IPSW
Product Version: 7.1.2
Product Build: 11D257 Major: 11
INFO: device serial number is DNRGT5LKDTC0
Device supports Image4: false
Custom firmware requested. Disabled TSS request.
Variant: Customer Upgrade Install (IPSW)
This restore will update your device without losing data.
Using cached filesystem from 'iPhone4,1_7.1.2_11D257_Restore/058-4365-009.dmg'
Extracting iBEC.n94ap.RELEASE.dfu...
Not personalizing component iBEC...
Sending iBEC (278924 bytes)...
Getting ApNonce in recovery mode... 24 cd ce 04 94 02 84 f0 3e 6e d8 ee 15 33 62 37 c9 09 1b 7b 
Recovery Mode Environment:
iBoot build-version=iBoot-2261.3.32
iBoot build-style=RELEASE
Sending AppleLogo...
Extracting applelogo@2x~iphone.s5l8940x.img3...
Not personalizing component AppleLogo...
Sending AppleLogo (6796 bytes)...
Extracting 058-4442-009.dmg...
Not personalizing component RestoreRamDisk...
Sending RestoreRamDisk (9584908 bytes)...
Extracting DeviceTree.n94ap.img3...
Not personalizing component RestoreDeviceTree...
Sending RestoreDeviceTree (81164 bytes)...
Extracting kernelcache.release.n94...
Not personalizing component RestoreKernelCache...
Sending RestoreKernelCache (8435788 bytes)...
About to restore device... 
Waiting for device...
ERROR: Unable to connect to device in restore mode
ERROR: Unable to open device in restore mode
ERROR: Unable to restore device

**Comment by goide** [comment]
@nikias 
Wich IOS version would work properly for iphone 4s? for restore.

**Comment by Itbnolehurr** [comment]
I was having the same problem. I looked YouTube and found a wonderful guy dedicated to helping people with these problems. Here is a link to his video that solved my problem: https://www.youtube.com/watch?v=FW9v1y5RTMw

**Comment by Sum1n** [comment]
you can use this video to fix this problem restore idevice on kali linux using libmobiledevice
https://www.youtube.com/watch?v=qRin2ggBGjw
