### ISSUE TITLE
Force flash to iphone

### ISSUE THREAD

**Issue by neuron1** [libimobiledevice/idevicerestore#205]
Iphones supposedly have a nonce that has to match with the nonce on the computer for an installation to work, to prevent re-using aptickets.

But I want to re use one.
The thing is, nonces are only checked during install time. If this can be bypassed once it will never be an issue again.
I would like to know if idevicerestore can simply force-write software to the iphone's NAND without authorization from the device, the way you would write software to a USB drive or something.

Take the choice of accepting or rejecting the software away from the iphone, and forcing the software onto it, whether it is signed or not (even though unsigned firmware won't work after doing this).

**Comment by Benfxmth** [comment]
No, idevicerestore can't force write software. You can use this if you know what you are doing if you have a 32 bit device:
https://www.reddit.com/r/jailbreak/comments/7v6pxu/release_tutorial_how_to_downgrade_any_32_bit/
