### ISSUE TITLE
Installing for a nobe

### ISSUE THREAD

**Issue by Itsxraze** [libimobiledevice/idevicerestore#209]
I am a new kali linux user and i don't really know how to install it and i did not understand the instructions so if some one write for me the commands and i just copy and past them in my terminal 
Thank You

**Comment by Itsxraze** [comment]
And can i bypass icloud because i have a locked ipad

**Comment by nikias** [comment]
The commands you need to run are literally in the README. Copy and paste. If you have all dependencies this will work. No iCloud bypass.
