### ISSUE TITLE
idevicerestore -e LINUX

### ISSUE THREAD

**Issue by Tor0nion** [libimobiledevice/idevicerestore#212]
idevicerestore -e doesnt work, i need to to reset my password on my ipad mini. Only idevicerestore -l works but it doesnt reset my password. When i type idevicerestore -e it just shows this..
latte@latte:~/Desktop/libplist-2.0.0$ sudo idevicerestore -e
Usage: idevicerestore [OPTIONS] FILE
Restore IPSW firmware FILE to an iOS device.

  -i, --ecid ECID	target specific device by its hexadecimal ECID
                 	e.g. 0xaabb123456 or 00000012AABBCCDD
  -u, --udid UDID	target specific device by its 40-digit device UDID
                 	NOTE: only works with devices in normal mode.
  -d, --debug		enable communication debugging
  -h, --help		prints usage information
  -e, --erase		perform a full restore, erasing all data (defaults to update)
  -c, --custom		restore with a custom firmware
  -l, --latest		use latest available firmware (with download on demand)
              		DO NOT USE if you need to preserve the baseband (unlock)!
              		USE WITH CARE if you want to keep a jailbreakable firmware!
              		The FILE argument is ignored when using this option.
  -s, --cydia		use Cydia's signature service instead of Apple's
  -x, --exclude		exclude nor/baseband upgrade
  -t, --shsh		fetch TSS record and save to .shsh file, then exit
  -k, --keep-pers	write personalized components to files for debugging
  -p, --pwn		put device in pwned DFU mode and exit (limera1n devices only)
  -n, --no-action	Do not perform any restore action. If combined with -l option
                 	the on demand ipsw download is performed before exiting.
  -C, --cache-path DIR	Use specified directory for caching extracted
                      	or other reused files.

**Comment by nikias** [comment]
You didn't even read the usage apparently. You need to pass a ipsw FILE on the command line or use -l to download the latest firmware. -e is just an additional option. So you can do
```idevicerestore -l -e```
or
```idevicerestore -e iPad_blah.ipsw```
