### ISSUE TITLE
'Savage SHSH' request seems need 'SEP' dict TAG, test on iPhone8

### ISSUE THREAD

**Issue by 4kzeng** [libimobiledevice/idevicerestore#214]
My iPhone 8 failed to  restore from iOS 11.3 beta3, it seems 'Savage request' need 'SEP' dict Tag appended.

**Comment by nikias** [comment]
So did you make any changes and it worked? Or are you not sure?

**Comment by 4kzeng** [comment]
I am not sure,  should wait for 'Apple' release the final version.

**Comment by nikias** [comment]
We don't want to wait for the final version; if there is something to add we should add it.

**Comment by 4kzeng** [comment]
Okey, In my iPhone8, it would stuck at 'ERROR: Unable to send FirmwareUpdater data', I  did some changes,  it could go again. See below:
//restore.c at line  1920
	
        plist_t tmp = plist_access_path(build_identity, 2, "Manifest", "SEP");
	if( tmp ){
		tmp = plist_copy(tmp);
		plist_dict_remove_item(tmp, "Info");		
		plist_dict_set_item(request, "SEP", tmp);
		tmp = NULL;
	}

	info("Sending Savage TSS request...\n");
	response = tss_request_send(request, client->tss_url);
	plist_free(request);

// But i am not sure it suitable for all case.

**Comment by nikias** [comment]
The SEP is already added to the Savage firmware request though only the Digest is copied:
https://github.com/libimobiledevice/idevicerestore/blob/master/src/tss.c#L819-L827
The other info shouldn't be relevant though, so I don't see why this would fail...

**Comment by nikias** [comment]
This issue should meanwhile be solved. Use latest code.
