### ISSUE TITLE
'ERROR: Unable to discover device model' on iPad 5 (2017)

### ISSUE THREAD

**Issue by iakdev** [libimobiledevice/idevicerestore#215]
iPad6,11 (J71tAP) won't get recorgnized correctly.

I get the follwoing ouput on macOS and Windows:

[INFO] 64bit device detected
futurerestore init done
reading ticket myshsh.shsh2 done
[Error] ERROR: Unable to discover device model
[Error] Fail code=-2
Failed with errorcode=-2

Edit: I was using encounter's fork of futurerestore, but I think it is idevicerestore related

**Comment by iakdev** [comment]
I think the problem might be that only "j71sap" but not "j71tap" for iPad6,11 is in libirecovery/src/libirecovery.c

**Comment by iakdev** [comment]
Adding

{"iPad6,11",  "j71tap", 0x10, 0x8003 },

to irecv_devices[] in said file fixed the problem for me.

**Comment by nikias** [comment]
Fixed with commit https://github.com/libimobiledevice/libirecovery/commit/260cb0684bf1cb7d2cdef8ce4a1ec6d832eb1d1c

**Comment by jailbreak2018** [comment]
I'm having the same issue but on mac, I was wondering if you could help me since I'm confused about the j71tap and other things thank you

**Comment by iakdev** [comment]
This isn’t a problem with libmobiledevice anymore.
encounter needs to update his futurerestore branch or you build it yourself from scratch using the latest libmobiledevice stack.

See https://github.com/encounter/futurerestore/issues/32
