### ISSUE TITLE
Help for restore iPhone 5c iOS 8.1.1 to 7.1.2

### ISSUE THREAD

**Issue by mcmuniz** [libimobiledevice/idevicerestore#23]
root@kali:/home/matheuscalixto/Desktop# idevicerestore iPhone5,4_7.1.2_11D257_Restore.ipsw
read_file: File cache/version.xml not found
ERROR: Could not load 'cache/version.xml'.
opening device 05ac:1281...
Setting to configuration 1
Setting to interface 0:0
Found device in Recovery mode
opening device 05ac:1281...
Setting to configuration 1
Setting to interface 0:0
INFO: device serial number is F2LLP8XJFFT7
ERROR: Unable to discover device type

**Comment by FunkyM** [comment]
Please post the output of a run with the "-d" debug flag.
Apart from that, it is not possible to downgrade an iPhone 5C from iOS 8.1.1 to 7.1.2.

**Comment by vinmas** [comment]
do you have a compiled version of idevicerestore? or a full guide to compile that?
thanks
