### ISSUE TITLE
./configure syntax error

### ISSUE THREAD

**Issue by Davidj361** [libimobiledevice/idevicerestore#25]
I did `autoconf configure.ac > configure; chmod +x configure; ./configure` but I'm getting this error.

```
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
./configure: line 1993: syntax error near unexpected token `ac_ext=c'
./configure: line 1993: `ac_ext=c'
```

**Comment by FunkyM** [comment]
It is unclear which platform you are using and you should run autogen.sh instead.
This looks like cygwin to me though which is not supported/tested at all.
You might try to install "autoconf-archive" to see if it fixes it for you or change to mingw.
