### ISSUE TITLE
pthread checks dont work on freebsd

### ISSUE THREAD

**Issue by sandhoners123** [libimobiledevice/idevicerestore#267]
configure does not add -lpthread to FreeBSD Makefile which is a bug

**Comment by nikias** [comment]
Usually AX_PTHREAD should take care of it. Can you post a full output of ./autogen.sh ?

**Comment by sandhoners123** [comment]
I removed freebsd since it kept segfaulting with all apps and it did not work with my wifi card. I think I had the same problem with ubuntu but let me just check that once

**Comment by nikias** [comment]
it definitely works with ubuntu. That's where I test it on.

**Comment by nikias** [comment]
@sandhoners123 any update here?

**Comment by sandhoners123** [comment]
I use fedora now lol
