### ISSUE TITLE
want to update firmware from windows computer

### ISSUE THREAD

**Issue by prateek1108** [libimobiledevice/idevicerestore#28]
Hello sir,
 i want to do the same work i.e. i want to update the usb connected ios device with windows computer.....how i can do this for windows....is his code i can use for windows also

**Comment by prateek1108** [comment]
Hello Sir,
I want to restore firmware of ios device.I had tried Idevicerestore Code with libimobiledevice in vc++ for windows and following is showing error in vc++ please help me out to built this project.
![idevicerestore](https://cloud.githubusercontent.com/assets/5064077/5869891/7bc9138c-a2e7-11e4-8a2f-be8bdde5d966.png)

**Comment by nikias** [comment]
Visual Studio is not supported.
