### ISSUE TITLE
Cant put into restore from DFU

### ISSUE THREAD

**Issue by khyfry** [libimobiledevice/idevicerestore#29]
No longer freezes on iBEC, no idea why. In su mode using sudo too, so maybe thats part of it.

Now I have a new problem! Yay...

sudo idevicerestore -d -c -e iPhone4,1_8.1.2_12B440_Restore.ipsw
Reading data from version.xml
NOTE: using cached version data
opening device 05ac:1227...
irecv_copy_nonce_with_tag: WARNING: couldn't find tag SNON in string  NONC:8B2D4E5F93D86D299D29D64A5D0945557A9405AE
Setting to configuration 1
Setting to interface 0:0
opening device 05ac:1227...
irecv_copy_nonce_with_tag: WARNING: couldn't find tag SNON in string  NONC:8B2D4E5F93D86D299D29D64A5D0945557A9405AE
Setting to configuration 1
Setting to interface 0:0
Found device in DFU mode
opening device 05ac:1227...
irecv_copy_nonce_with_tag: WARNING: couldn't find tag SNON in string  NONC:8B2D4E5F93D86D299D29D64A5D0945557A9405AE
Setting to configuration 1
Setting to interface 0:0
Identified device as iPhone4,1
Extracting Restore.plist from IPSW
Product Version: 8.1.2
Product Build: 12B440 Major: 12
opening device 05ac:1227...
irecv_copy_nonce_with_tag: WARNING: couldn't find tag SNON in string  NONC:8B2D4E5F93D86D299D29D64A5D0945557A9405AE
Setting to configuration 1
Setting to interface 0:0
Device supports Image4: false
Custom firmware requested. Disabled TSS request.
Variant: Customer Erase Install (IPSW)
This restore will erase your device data.
Using cached filesystem from 'iPhone4,1_8.1.2_12B440_Restore/058-09779-017.dmg'
opening device 05ac:1227...
irecv_copy_nonce_with_tag: WARNING: couldn't find tag SNON in string  NONC:8B2D4E5F93D86D299D29D64A5D0945557A9405AE
Setting to configuration 1
Setting to interface 0:0
Extracting iBSS.n94ap.RELEASE.dfu...
Not personalizing component iBSS...
Writing data to iBSS
Sending iBSS (78220 bytes)...
[==================================================] 100.0%
opening device 05ac:1227...
irecv_copy_nonce_with_tag: WARNING: couldn't find tag SNON in string  NONC:8B2D4E5F93D86D299D29D64A5D0945557A9405AE
Setting to configuration 1
Setting to interface 0:0
Nonce: 8b 2d 4e 5f 93 d8 6d 29 9d 29 d6 4a 5d 09 45 55 7a 94 05 ae 
Setting to configuration 1
Extracting iBEC.n94ap.RELEASE.dfu...
Not personalizing component iBEC...
Writing data to iBEC
Sending iBEC (283020 bytes)...
[==================================================] 100.0%
opening device 05ac:1227...
irecv_copy_nonce_with_tag: WARNING: couldn't find tag SNON in string  NONC:8B2D4E5F93D86D299D29D64A5D0945557A9405AE
Setting to configuration 1
Setting to interface 0:0
ERROR: Unable to connect to recovery device
ERROR: Unable to place device into recovery mode from DFU mode

 same happens without -c.

Stays in DFU mode too.

**Comment by Charyas** [comment]
I get the same trouble. do you get the more discover?

**Comment by nikias** [comment]
Custom firmware with 4s doesn't work.
