### ISSUE TITLE
Support restore of T2 devices in DFU

### ISSUE THREAD

**Issue by rickmark** [libimobiledevice/idevicerestore#298]
The listing of IPSW for the T2 is here:

https://mesu.apple.com/assets/bridgeos/com_apple_bridgeOSIPSW/com_apple_bridgeOSIPSW.xml

Should be trivial to add support for restoring T2 chips.

**Comment by rickmark** [comment]
https://github.com/libimobiledevice/idevicerestore/pull/300
https://github.com/libimobiledevice/usbmuxd/pull/128
https://github.com/libimobiledevice/libirecovery/pull/55

**Comment by rickmark** [comment]
Combined with https://mesu.apple.com/assets/bridgeos/com_apple_bridgeOSIPSW/com_apple_bridgeOSIPSW.xml allows for successful restore of T2 firmware

**Comment by nikias** [comment]
All done now.
