### ISSUE TITLE
deleted

### ISSUE THREAD

**Issue by Duplicitious** [libimobiledevice/idevicerestore#305]
deleted

**Comment by Codyp1996** [comment]
Im having the same issue with an Apple Tv 4. Have you figured anything out? Im running on linux.

**Comment by nikias** [comment]
I bet that usbmuxd is not running. Try running it in foreground in another terminal to see if that helps: ```sudo usbmuxd -f```
I am seeing some issues with systemd recently...

**Comment by Duplicitious** [comment]
Yep that fixed it @nikias . Also do you know how to reset the devices apple ID?

**Comment by nikias** [comment]
If you are talking about iCloud lock aka activation lock it is something that I can't help you with.

**Comment by JosephBellfixit** [comment]
> I bet that usbmuxd is not running. Try running it in foreground in another terminal to see if that helps: `sudo usbmuxd -U usbmux -f`
> I am seeing some issues with systemd recently...



> I bet that usbmuxd is not running. Try running it in foreground in another terminal to see if that helps: `sudo usbmuxd -U usbmux -f`
> I am seeing some issues with systemd recently...

Great help, running it in the background solved the issue straight away.
