### ISSUE TITLE
ERROR: Unable to connect to FDR client (-2)

### ISSUE THREAD

**Issue by zcx2020** [libimobiledevice/idevicerestore#316]
Just restored iPad Mini 1 using idevicerestore on Linux Mint 19.3 x64.

Built the following from latest sources with no errors...
libplist
usbmuxd
libusbmuxd
libimobiledevice
idevicerestore

Created udev rule, rebooted.

Put device in recovery mode.

In terminal #1...

$ sudo usbmuxd -vv -f output

(Just in case systemd doesn't start usbmuxd)

In terminal #2...

$ idevicerestore -e ./iPad2,5_9.3.5_13G36_Restore.ipsw

Using .ipsw from a previous run.

All looks good until here...

...
ProductionMode: true
Previous restore exit status: 0x100
Starting FDR listener thread
ERROR: Unable to connect to FDR client (-2)
ERROR: Failed to start FDR Ctrl channel
...

After that restore completed successfully, in spite of these errors.  Device now appears to work normally.

Can anyone shed any light on this?

What is the FDR Ctrl channel?

**Comment by zhou0** [comment]
i get the same error. how do you fix it?
