### ISSUE TITLE
2nd Generation iPod Touch restore to 4.2.1 fails

### ISSUE THREAD

**Issue by ureru** [libimobiledevice/idevicerestore#33]
4.2.1 is the latest version available for a second generation ipod touch. Also, I am using Debian Jessie.

idevicerestore -dce iPod2,1_4.2.1_8C148_Restore.ipsw
Reading data from version.xml
NOTE: using cached version data
opening device 05ac:1227...
irecv_copy_nonce_with_tag: WARNING: couldn't find tag NONC in string Apple Inc.
irecv_copy_nonce_with_tag: WARNING: couldn't find tag SNON in string Apple Inc.
Setting to configuration 1
Setting to interface 0:0
opening device 05ac:1227...
irecv_copy_nonce_with_tag: WARNING: couldn't find tag NONC in string Apple Inc.
irecv_copy_nonce_with_tag: WARNING: couldn't find tag SNON in string Apple Inc.
Setting to configuration 1
Setting to interface 0:0
Found device in DFU mode
opening device 05ac:1227...
irecv_copy_nonce_with_tag: WARNING: couldn't find tag NONC in string Apple Inc.
irecv_copy_nonce_with_tag: WARNING: couldn't find tag SNON in string Apple Inc.
Setting to configuration 1
Setting to interface 0:0
ERROR: Unable to discover device type

**Comment by nikias** [comment]
This should be fixed now with the commit from https://github.com/libimobiledevice/libirecovery/pull/36
