### ISSUE TITLE
[question] does it works with iPod Nano 7th gen ? 

### ISSUE THREAD

**Issue by Lion4K** [libimobiledevice/idevicerestore#335]
I only have a raspberry pi and I really need to restore a couple of iPods.

**Comment by nikias** [comment]
Hi, it is not compatible with the nano 7th gen since it uses a different system.

**Comment by Lion4K** [comment]
oh i see, only ios devices.
thanks!!

**Comment by Lion4K** [comment]
oh yeah, do you know any alternative?

**Comment by nikias** [comment]
No, sorry.
