### ISSUE TITLE
Unable restore iphone 6 and 6 plus without SIM card

### ISSUE THREAD

**Issue by skyeyes25** [libimobiledevice/idevicerestore#34]
The version (Oct 28, 2014) of idevicerestore can't restore iphone 6 and 6 plus if there in no SIM. The phone return AMRError with status is 56.

**Comment by FunkyM** [comment]
Should be fixed in git master. It doesn't matter whether a SIM was inserted, the code wasn't ready for these device models.
It always helps if you also supply more information around the OS and versions of idevicerestore and it's dependencies.
