### ISSUE TITLE
idevicerestore: undefined symbol: preboard_client_new

### ISSUE THREAD

**Issue by Texlo-Dev** [libimobiledevice/idevicerestore#340]
Hey all, compiled and installed idevicerestore recently. Tried to run `idevicerestore -l` and I get the following error: 

```
idevicerestore: undefined symbol: preboard_client_new
```

What does this mean? For reference, I'm on Ubuntu 18.04 LTS.

**Comment by grayguest** [comment]
> Hey all, compiled and installed idevicerestore recently. Tried to run `idevicerestore -l` and I get the following error:
> 
> ```
> idevicerestore: undefined symbol: preboard_client_new
> ```
> 
> What does this mean? For reference, I'm on Ubuntu 18.04 LTS.

hello, i met the same problem, can you tell me some solution policy?

**Comment by nikias** [comment]
libimobiledevice is too old and you need to compile an updated version yourself.
