### ISSUE TITLE
how to jailbreak macbook

### ISSUE THREAD

**Issue by vnn567** [libimobiledevice/idevicerestore#349]
![h1](https://user-images.githubusercontent.com/23457468/85740224-a5b80a00-b72b-11ea-9fdb-3b6df1bfd1a7.jpg)
![h2](https://user-images.githubusercontent.com/23457468/85740240-a94b9100-b72b-11ea-8c91-5e06567b5747.jpg)

**Comment by nikias** [comment]
Wrong issue tracker.
