### ISSUE TITLE
usbmuxd_get_device_list: error opening socket

### ISSUE THREAD

**Issue by kaboramb** [libimobiledevice/idevicerestore#35]
Hello,

I tried to use idevicerestore but I got this error 

Extracting kernelcache.release.n94
Writing data to kernelcache.release.n94
Sending RestoreKernelCache (9064396 bytes)...
[==================================================] 100.0%
About to restore device... 
waiting for device...
trying to connect...
usbmuxd_get_device_list: error opening socket!
usbmuxd_get_device_list: error opening socket!
usbmuxd_get_device_list: error opening socket!
usbmuxd_get_device_list: error opening socket!
usbmuxd_get_device_list: error opening socket!
usbmuxd_get_device_list: error opening socket!
usbmuxd_get_device_list: error opening socket!
usbmuxd_get_device_list: error opening socket!
usbmuxd_get_device_list: error opening socket!
usbmuxd_get_device_list: error opening socket!
usbmuxd_get_device_list: error opening socket!
usbmuxd_get_device_list: error opening socket!
usbmuxd_get_device_list: error opening socket!
usbmuxd_get_device_list: error opening socket!
usbmuxd_get_device_list: error opening socket!
usbmuxd_get_device_list: error opening socket!
usbmuxd_get_device_list: error opening socket!
usbmuxd_get_device_list: error opening socket!
usbmuxd_get_device_list: error opening socket!
usbmuxd_get_device_list: error opening socket!
hm... could not connect
ERROR: Unable to open device in restore mode
ERROR: Unable to restore device

Can you help me please?any idea?

Thanks

**Comment by FunkyM** [comment]
Which operating system?
How did you compile idevicerestore?
Are you running usbmuxd as super user?
