### ISSUE TITLE
compilation error on the latest version of idevicerestore on windows

### ISSUE THREAD

**Issue by iFred09** [libimobiledevice/idevicerestore#350]
Hello,

I'm trying to compile the latest commit of idevicerestore and I have this error, and I never had this error before (i successfully compiled this two months ago).
Same error when I compile with the version in the "Release" tab.

![compileerroridevicerestore](https://user-images.githubusercontent.com/22419166/85959334-22e9b600-b99c-11ea-94e9-9b18e9a6bea9.png)

Thank's!

**Comment by nikias** [comment]
Well the configure script sets `-O2` which is clearly not negative. You can run `make V=1` to get verbose output and check what it passes as `-O`.

**Comment by iFred09** [comment]
I got this when I run `make V=1` :

![compileerroridevicerestore2](https://user-images.githubusercontent.com/22419166/86511571-cb63a400-bdfa-11ea-938b-56750d4f448b.png)

**Comment by nikias** [comment]
As you can see in the output there's a `-O2-DWIN32` which lacks a space.
I will commit a change adding a space here: https://github.com/libimobiledevice/idevicerestore/blob/master/configure.ac#L56

**Comment by nikias** [comment]
See ac01193.
