### ISSUE TITLE
Not able to restore multiple devices at the same time

### ISSUE THREAD

**Issue by rajeevs12** [libimobiledevice/idevicerestore#374]
Hello ,
we are trying to restore 2 devices at the same time and getting below error on both devices. Can anyone help here what we are doing wrong .We have latest idevicerestore executable and running it on windows 10.
Attached output of both devices.

[iPhone6sOutput.txt](https://github.com/libimobiledevice/idevicerestore/files/5406154/iPhone6sOutput.txt)
[iphone11output.txt](https://github.com/libimobiledevice/idevicerestore/files/5406156/iphone11output.txt)

**Comment by nikias** [comment]
Seems like the code fails to get the device ECID when you pass the UDID. I suggest using `-i <ECID>` instead of using UDID until this issue is fixed.

**Comment by nSneerfulBike** [comment]
Have you managed to get it working for Windows? For me it doesn't even work with one device

**Comment by rajeevs12** [comment]
> Seems like the code fails to get the device ECID when you pass the UDID. I suggest using `-i <ECID>` instead of using UDID until this issue is fixed.

Hi @nikias Thank you this is  working fine now  with <ECID> option. But<ECID> works when device is in recovery mode .What we are doing now first we send restore command to device with UDID and its get failed and turn the device  into  recovery mode. We then send second restore command on device with <ECID>and it works fine. Is there any command to send device into recovery mode directly from normal mode ?

**Comment by rajeevs12** [comment]
> Have you managed to get it working for Windows? For me it doesn't even work with one device

Yes it is working fine with single device on windows 10.

**Comment by nSneerfulBike** [comment]
> > Have you managed to get it working for Windows? For me it doesn't even work with one device
> 
> Yes it is working fine with single device on windows 10.

Can you tell me what library are you using and where did you get it?

**Comment by a-gunter** [comment]
> > Seems like the code fails to get the device ECID when you pass the UDID. I suggest using `-i <ECID>` instead of using UDID until this issue is fixed.
> 
> Hi @nikias Thank you this is working fine now with `-i <ECID>` option. But '`-i <ECID>` works when device is in recovery mode .What we are doing now first we send restore command to device with UDID and its get failed and turn the device into recovery mode. We then send second restore command on device with `-i <ECID>` and it works fine. Is there any command to send device into recovery mode directly from normal mode ?

Use the ideviceenterrecovery tool from libimobiledevice:
`ideviceenterrecovery -u {UDID}`

**Comment by rajeevs12** [comment]
> > > Seems like the code fails to get the device ECID when you pass the UDID. I suggest using `-i <ECID>` instead of using UDID until this issue is fixed.
> > 
> > 
> > Hi @nikias Thank you this is working fine now with `-i <ECID>` option. But '`-i <ECID>` works when device is in recovery mode .What we are doing now first we send restore command to device with UDID and its get failed and turn the device into recovery mode. We then send second restore command on device with `-i <ECID>` and it works fine. Is there any command to send device into recovery mode directly from normal mode ?
> 
> Use the ideviceenterrecovery tool from libimobiledevice:
> `ideviceenterrecovery -u {UDID}`

Many thanks

**Comment by rajeevs12** [comment]
> > > > Seems like the code fails to get the device ECID when you pass the UDID. I suggest using `-i <ECID>` instead of using UDID until this issue is fixed.
> > > 
> > > 
> > > Hi @nikias Thank you this is working fine now with `-i <ECID>` option. But '`-i <ECID>` works when device is in recovery mode .What we are doing now first we send restore command to device with UDID and its get failed and turn the device into recovery mode. We then send second restore command on device with `-i <ECID>` and it works fine. Is there any command to send device into recovery mode directly from normal mode ?
> > 
> > 
> > Use the ideviceenterrecovery tool from libimobiledevice:
> > `ideviceenterrecovery -u {UDID}`
> 
> Many thanks

**Comment by rajeevs12** [comment]
> > > Have you managed to get it working for Windows? For me it doesn't even work with one device
> > 
> > 
> > Yes it is working fine with single device on windows 10.
> 
> Can you tell me what library are you using and where did you get it?

we get them from https://github.com/libimobiledevice

**Comment by nSneerfulBike** [comment]
> > > > Have you managed to get it working for Windows? For me it doesn't even work with one device
> > > 
> > > 
> > > Yes it is working fine with single device on windows 10.
> > 
> > 
> > Can you tell me what library are you using and where did you get it?
> 
> we get them from https://github.com/libimobiledevice

What did you use to compile it? I am really struggling to find a way to compile it on Windows

**Comment by airwolf2026** [comment]
> > > > > Have you managed to get it working for Windows? For me it doesn't even work with one device
> > > > 
> > > > 
> > > > Yes it is working fine with single device on windows 10.
> > > 
> > > 
> > > Can you tell me what library are you using and where did you get it?
> > 
> > 
> > we get them from https://github.com/libimobiledevice
> 
> What did you use to compile it? I am really struggling to find a way to compile it on Windows

Using VS Code or Visual studio ,
If you don't want to change a lot warning or errors,
you hava to set a lot predefine marco like '_CRT_SECURE_NO_WARNINGS
_WINSOCK_DEPRECATED_NO_WARNINGS' .
