### ISSUE TITLE
Iphone 4s, restore IOS 8.3

### ISSUE THREAD

**Issue by goide** [libimobiledevice/idevicerestore#38]
****_@**_:~# sudo idevicerestore -e '/root/Desktop/iPhone4,1_8.3_12F70_Restore.ipsw' 
read_file: File cache/version.xml not found
ERROR: Could not load 'cache/version.xml'.
opening device 05ac:1281...
Setting to configuration 1
Setting to interface 0:0
Found device in Recovery mode
opening device 05ac:1281...
Setting to configuration 1
Setting to interface 0:0
INFO: device serial number is XXXXXXXXXXXX
Identified device as iPhone4,1
Extracting BuildManifest from IPSW
ERROR: zip_name_locate: BuildManifesto.plist
Product Version: 8.3
Product Build: 12F70
Variant: Customer Erase Install (IPSW)
This restore will erase your device data.
Found ECID 2439408448904
checking for local shsh
no local file shsh/2439408448904-iPhone4,1-8.3.shsh
Trying to fetch new SHSH blob
TSS server returned: STATUS=94&MESSAGE=This device isn't eligible for the requested build.
ERROR: TSS request failed (status=94)
Sending TSS request... ERROR: Unable to send TSS request
ERROR: Unable to get SHSH blobs for this device

Which means that error status=94? or error TSS?

**Comment by aburgh** [comment]
8.3 is no longer being signed by Apple. Try downloading 8.4 and installing that.

**Comment by goide** [comment]
root@kali:~# sudo idevicerestore -e '/root/Desktop/iPhone4,1_8.4_12H143_Restore.ipsw'  
read_file: File cache/version.xml not found
ERROR: Could not load 'cache/version.xml'.
opening device 05ac:1281...
Setting to configuration 1
Setting to interface 0:0
Found device in Recovery mode
opening device 05ac:1281...
Setting to configuration 1
Setting to interface 0:0
INFO: device serial number is XXXXXXXXXXXXX
Identified device as iPhone4,1
Extracting BuildManifest from IPSW
ERROR: zip_name_locate: BuildManifesto.plist
Product Version: 8.4
Product Build: 12H143
Variant: Customer Erase Install (IPSW)
This restore will erase your device data.
Found ECID 2439408448904
checking for local shsh
no local file shsh/2439408448904-iPhone4,1-8.4.shsh
Trying to fetch new SHSH blob
Sending TSS request... received SHSH blobs
Extracting filesystem from IPSW
[==================================================] 100.0%
ERROR: Unable to find iBEC entry in TSS response
iBEC will be signed
Extracting iBEC.n94.RELEASE.dfu
ERROR: Unable to find iBEC entry in TSS response
ERROR: Unable to get SHSH blob for TSS iBEC.n94.RELEASE.dfu entry
ERROR: Unable to get component: iBEC
ERROR: Unable to send iBEC to device.
ERROR: Unable to send iBEC

**Comment by goide** [comment]
Now I get this error , you believe it ?

**Comment by prateek1108** [comment]
i am also facing the same issue i.e.

Error: Unable to get component: iBEC
Error: Unable to send iBEC to device
Error: Unable to send iBEC

for iphone6,2_8.4_12H143_Rstore.ipsw


please help me out how i can remove this error and erase and update iphone.

**Comment by FunkyM** [comment]
Which operating system are you using and how did you compile idevicerestore?

**Comment by giorgosvas** [comment]
hi.please i am trying to restore firmware on an iphone 5 and i have this problem:
root@kali:~/idevicerestore# idevicerestore -e iPhone5,2_7.1.2_11D257_Restore.ipsw
read_file: File cache/version.xml not found
ERROR: Could not load 'cache/version.xml'.
opening device 05ac:1281...
Setting to configuration 1
Setting to interface 0:0
Found device in Recovery mode
opening device 05ac:1281...
Setting to configuration 1
Setting to interface 0:0
INFO: device serial number is F2NJQ3P9DTWH
ERROR: Unable to discover device type
 please can you help me i dont know what to do
thanks in advance

**Comment by Gaby4** [comment]
The same problem with iphone 5C(5,3) ,iPhone5,3_9.0.2_13A452_Restore.ipsw

Any update with the issue?


TSS server returned: STATUS=94&MESSAGE=This device isn't eligible for the requested build.
ERROR: TSS request failed (status=94)
Sending TSS request... ERROR: Unable to send TSS request
ERROR: Unable to get SHSH blobs for this device
