### ISSUE TITLE
ios14.3~14.4: Unknown data request 'PersonalizedData' received

### ISSUE THREAD

**Issue by karin722** [libimobiledevice/idevicerestore#396]
>device: iphone 6s
ios: 14.3
PC: manjaro (arch)
idevicerestore: latest ([aur](https://aur.archlinux.org/packages/idevicerestore-git))

https://github.com/libimobiledevice/idevicerestore/issues/362 The above issue again...

**Comment by karin722** [comment]
A similar error occurred in IOS 14.4.

**Comment by karin722** [comment]
I'm sorry. It seems that the aur I was using was old. I compiled the latest version and it works fine.

**Comment by karin722** [comment]
I'm sorry. It seems that the aur I was using was old. I compiled the latest version and it works fine.

**Comment by hkokarma** [comment]
Same here, iPhone 6 S. It goes 50% then 
"Unknown data request 'PersonalizedData' received" and stops. 
No solution?
