### ISSUE TITLE
ERROR: tss_send_request: Unhandled status code 162

### ISSUE THREAD

**Issue by Py-Tommy** [libimobiledevice/idevicerestore#399]
[TSSC] opening /tmp/futurerestore/basebandManifest.plist
[TSSR] Checking BuildIdentity 0
[TSSR] Selected BuildIdentity for request
[TSSR] User specified to request only a Baseband ticket.

[TSSR] Found undocumented baseband

Request URL set to https://gs.apple.com/TSS/controller?action=2
TSS server returned: STATUS=162&MESSAGE=An internal error occurred.
ERROR: tss_send_request: Unhandled status code 162
Sending TSS request attempt 1... Request URL set to https://17.171.36.30/TSS/controller?action=2

**Comment by nikias** [comment]
Wrong project.
