### ISSUE TITLE
Unable to fetch tss for Rose (This device isn't eligible for the requested build.)

### ISSUE THREAD

**Issue by hinoble** [libimobiledevice/idevicerestore#401]
I have some problem with iPhone 11 and 12 (previous  models work)
I use the -l (latest option) ipsw is downloaded from apple, but I am getting this error:
```
Updating Rose (65)

Sending Rose TSS request...

Request URL set to https://gs.apple.com/TSS/controller?action=2

TSS server returned: STATUS=94&MESSAGE=This device isn't eligible for the requested build.

ERROR: TSS request failed (status=94, message=This device isn't eligible for the requested build.)

ERROR: Unable to fetch Rose ticket
```
iTunes restore without problem. 

Probably there was an update for this chip, but I have missed it (I have all latest patches), could someone point me where to look for solution?

Here is the TSS request that is being sent and it seems like there are many things missing. tss.c is completely updated.

[request.txt](https://github.com/libimobiledevice/idevicerestore/files/6148560/request.txt)
[build_identity.txt](https://github.com/libimobiledevice/idevicerestore/files/6148566/build_identity.txt)
[parameters.txt](https://github.com/libimobiledevice/idevicerestore/files/6148571/parameters.txt)

**Comment by hinoble** [comment]
I have updated the question with more debug data. Please can someone help me?

**Comment by hinoble** [comment]
Ok I have found the problem: the Rap,BoardID and Rap,ChipID values are wrong (read from parameters.plist). Not sure what caused this though.

**Comment by nikias** [comment]
It looks like an endian problem, parameters has them as data nodes, for example the Rap,ChipID is 06 20 in bytes, the integer value is 8198 which is 0x2006 in hex. I need to check where the conversion happens.

**Comment by hinoble** [comment]
Sorry Nikias, just found MY problem (as usual) - this was old libplist, it was not reading the values correctly. Updated libplist and now it works. Sorry for your list time.

**Comment by nikias** [comment]
No worries, I didn't check yet :)

**Comment by hinoble** [comment]
oh, I was too fast with conclusion, i just put the Rose functions in a test and tested before starting restore

```
	restore_get_rose_firmware_data(restore, client, build_identity, NULL);

	return 0;

	// start the restore process
```

This way the values were reading correct:

```
        <key>Rap,BoardID</key>
        <integer>8</integer>
        <key>Rap,ChipID</key>
        <integer>8198</integer>
        <key>Rap,ECID</key>
        <integer>-1</integer>
```

but after running a test I've got this again:

```
        <key>Rap,BoardID</key>
        <integer>2048</integer>
        <key>Rap,ChipID</key>
        <integer>1568</integer>
        <key>Rap,ECID</key>
        <integer>4325429784801731584</integer>
```

Probably this code makes the problem:

```
	/* add Rap,* tags from info dictionary to parameters */
	plist_dict_merge(&parameters, p_info);
```

If you are still here we can debug together.

**Comment by hinoble** [comment]
You were right. I forgot to set __LITTLE_ENDIAN__ in idevicerestore project.

**Comment by xing181512** [comment]
@hinoble  I also have the same problem, tss.c and  libplist  is completely updated. how you solved it？

**Comment by CyberOneLPDN** [comment]
Hello i'm facing the same problem 

TSS server returned: STATUS=94&MESSAGE=This device isn't eligible for the requested build.

and i'm searching for solution to fix it 
do you find why it doesn't work ?
