### ISSUE TITLE
What exactly issue for Unknown data request 'BasebandUpdaterOutputData' received

### ISSUE THREAD

**Issue by gsmdenis** [libimobiledevice/idevicerestore#404]
hi,

What exactly issue for Unknown data request 'BasebandUpdaterOutputData' received !!!

**Comment by gsmdenis** [comment]
after update itunes, get could not read data (-256)

**Comment by nikias** [comment]
From what I can tell, the device sends this when the baseband update failed. The latest code handles this (but it won't fix your error, which seems to be something with the device itself).
