### ISSUE TITLE
idevicerestore: symbol lookup error: idevicerestore: undefined symbol: irecv_send_command_breq

### ISSUE THREAD

**Issue by tmhgh** [libimobiledevice/idevicerestore#419]
idevicerestore: symbol lookup error: idevicerestore: undefined symbol: irecv_send_command_breq

I get this error when I try to run idevicerestore. Built from the latest clone from this repo

**Comment by nikias** [comment]
You need latest code for libirecovery as well.

**Comment by tmhgh** [comment]
I am

**Comment by tmhgh** [comment]
Thanks for the reply, I am using the latest from the github repos of all these, libplist, libusbmuxd, libimobiledevice, and libirecovery.

**Comment by nikias** [comment]
You probably have another libirecovery still around. Make sure it uses the right one. Here's the commit:
https://github.com/libimobiledevice/libirecovery/commit/47934949e0015165a4562b08e824adb3f664c0ea

**Comment by tmhgh** [comment]
Okay, thanks I'll check it out.

**Comment by tmhgh** [comment]
Thanks, that was the problem. I have a libirecovery from a different repo lying about, Thanks again
