### ISSUE TITLE
There have a bug in recovery.c

### ISSUE THREAD

**Issue by xdayong** [libimobiledevice/idevicerestore#422]
At line 125
```
        if (client->build_major >= 8) {
		client->restore_boot_args = strdup("rd=md0 nand-enable-reformat=1 -progress");
	} else if (client->build_major >= 20) {
		client->restore_boot_args = strdup("rd=md0 nand-enable-reformat=1 -progress -restore");
	}
```
`if (client->build_major >= 8) `
should be changed to 
`if (client->build_major >= 8 && client->build_major<20)`

**Comment by nikias** [comment]
Hi, do you get error messages with the original code? Your change makes perfect sense though.

**Comment by xdayong** [comment]
Oh,I didn't got any error, I just see the logic is wrong.

**Comment by nikias** [comment]
alright, let me fix this...
