### ISSUE TITLE
change the RestoreOptions, restore recive the same messages. how to change this?

### ISSUE THREAD

**Issue by xiaojiangDraug** [libimobiledevice/idevicerestore#44]

**Comment by nikias** [comment]
You can't. The restore options are ignored by restored (the daemon running on the device that controls the actual restore process) and it is using its own hardcoded set of restore options.

**Comment by xiaojiangDraug** [comment]
thank you for your answer!

**Comment by xiaojiangDraug** [comment]
thank you!

**Comment by DarkUD** [comment]
Can you think of a reason why a device can not go into restore mode from recovery mode ?

**Comment by xiaojiangDraug** [comment]
I think the phone maybe in lockdownd, the recovery command requests will be refused. Do you get the error logs？

**Comment by DarkUD** [comment]
I only get waiting for device and it is stuck in recovery mode since I received it. I tho that might be a device problem. What does it means it is in lockdown ? and how to fix that ?

**Comment by FunkyM** [comment]
Please don't abuse the ticket title for your question!
Please don't discuss or ask off-topic questions rather create your own ticket for it.
On topic, as noted by Nikias, you can't set the options on production firmwares.
They only work on Debug and Factory ones.
