### ISSUE TITLE
iPhone13 'This device isn't eligible for the requested build'

### ISSUE THREAD

**Issue by XanaduAPI** [libimobiledevice/idevicerestore#447]
I brush the machine with the latest code.

Brush iphone6-iphone12 normally.

But when I tried the iPhone 13, the program made an error.

The following is the brush log.

[idevicerestore.log](https://github.com/libimobiledevice/idevicerestore/files/7252326/idevicerestore.log)

**Comment by nikias** [comment]
Looks like Apple's TSS server is having issues. Nothing we can do except wait for them to fix it.

**Comment by XanaduAPI** [comment]
You should be right. I tried to recover using iTunes. An error occurred: unknown error (3194)
