### ISSUE TITLE
idevicerestore not responding (Windows 10)

### ISSUE THREAD

**Issue by hiepnh0** [libimobiledevice/idevicerestore#470]
Restoring is done on the phone but idevicerestore process is not responding.
iPhone 5S, 
iOS 12.5.5
Windows 10
//////
Here is the output:
...
Checkpoint 1630 complete with code 0
Checkpoint 5377 complete with code 0
Checkpoint 5376 complete with code 0
Checkpoint 1640 complete with code 0
Checkpoint 1597 complete with code 0
Checkpoint 1599 complete with code 0
Checkpoint 1600 complete with code 0
Checkpoint 1641 complete with code 0
Unmounting filesystems (29)
Unmounting filesystems (29)
Unmounting filesystems (29)
Checkpoint 1602 complete with code 0
Checkpoint 1607 complete with code 0
Got status message
Status: Restore Finished
ReverseProxy[Ctrl]: (status=2) Terminated

**Comment by ashishgah** [comment]
same issue, kindly reply a solution please.

**Comment by hiepnh0** [comment]
> same issue, kindly reply a solution please.

Comment this line: https://github.com/libimobiledevice/idevicerestore/issues/471#issue-1169167235

**Comment by 100rb** [comment]
Getting same issue after updating libidevicerestore library, device is restoring successfully but command is not exiting.

Error :
Checkpoint 4294968893 complete with code 0
Checkpoint 4294968895 complete with code 0
Checkpoint 38654707264 complete with code 0
Checkpoint 1641 complete with code 0
Unmounting filesystems (29)
Unmounting filesystems (29)
Unmounting filesystems (29)
Unmounting filesystems (29)
Checkpoint 1602 complete with code 0
Checkpoint 1607 complete with code 0
Got status message
Status: Restore Finished
ReverseProxy[Conn]: (status=2) Terminated


When using previous library getting success response as below and command is also exiting

Checkpoint 4294968896 complete with code 0
Checkpoint 4294968937 complete with code 0
Unmounting filesystems (29)
Unmounting filesystems (29)
Unmounting filesystems (29)
Unmounting filesystems (29)
Checkpoint 4294968898 complete with code 0
Checkpoint 1607 complete with code 0
Got status message
Status: Restore Finished
Cleaning up...
DONE

**Comment by 100rb** [comment]
Checked

> This issue is fixed with sandin patch for libusbmuxd : https://github.com/libimobiledevice/libusbmuxd/pull/125/commits

Checked for iPhone 6 working fine.
Thanks @Orbif
