### ISSUE TITLE
Can not get idevicerestore to run

### ISSUE THREAD

**Issue by lothsun** [libimobiledevice/idevicerestore#49]
I get this error when running idevicerestore from terminal.

idevicerestore: error while loading shared libraries: libirecovery.so.2: cannot open shared object file: No such file or directory

How do I fix this problem?

**Comment by DarkUD** [comment]
try using ldconfig when you install libimobiledevice

**Comment by FunkyM** [comment]
Recompile idevicerestore and verify your libirecovery installation using ldd on the binary.
If you don't know what I am talking about you better start off from zero, get all sources/dependencies and recompile.
