### ISSUE TITLE
32 bit cannot request memory.

### ISSUE THREAD

**Issue by xanadu-lee** [libimobiledevice/idevicerestore#497]
In restore_send_source_boot_object_v4, it is not possible to request more than 2GB of memory.
I wonder if it is possible to consider applying by segment?
Because the transfer is in 8192 bytes.

![image](https://user-images.githubusercontent.com/45027459/174426459-c26b86f1-2885-4e70-9520-4d4a2aff5309.png)
![image](https://user-images.githubusercontent.com/45027459/174426472-48ebf140-aab5-43d0-ac61-c5ee430faf2f.png)

If the system does not allow memory allocation, extract_component fails.

**Comment by xing181512** [comment]
I have the same problem, have you solved it?

**Comment by xanadu-lee** [comment]
Solved by modifying the code.
When I decompressed at one time, I didn't actually decompress it, and then every time I sent it, I pressed the mark to decompress it.

**Comment by nikias** [comment]
In the past we didn't have such large components so this wasn't a problem. Ideally the code needs to be changed to stream the data directly while decompressing from zip, or at least extract the image to disk first.

**Comment by xanadu-lee** [comment]
@nikias 
I've solved it myself, and since I don't know the whole process well, I think you must have a more elegant solution.
