### ISSUE TITLE
not compatible with 16.0b2 ipsw's - error Cryptex1LocalPolicy

### ISSUE THREAD

**Issue by sitay1** [libimobiledevice/idevicerestore#506]
ERROR: restore_send_firmware_updater_data: Got unknown updater name 'Cryptex1LocalPolicy'.
Running on bigsur 11.5.2 

`
devicerestore 1.0.0-97-ge65d34b
Found device in Recovery mode
Identified device as d64ap, iPhone14,3
Extracting BuildManifest from IPSW
Product Version: 16.0
Product Build: 20A5303i Major: 20
INFO: device serial number is H9LLJ77F4G
Device supports Image4: true
Variant: Developer Upgrade Install (IPSW)
This restore will update your device without erasing user data.
Checking IPSW for required components...
All required components found in IPSW
Using cached filesystem from '/Volumes/Samsung_T5/binaries/ipsw/16b2/iPhone14,3_16.0_20A5303i_Restore/078-13971-055.dmg'
Found ECID 5147742653087774
Getting ApNonce in recovery mode... c6 17 53 d8 da 60 73 f2 92 a7 48 16 7d d5 62 ad ec 93 74 d2 61 15 20 ce f6 ce 42 9d 6f f0 a8 03
Trying to fetch new SHSH blob
Getting SepNonce in recovery mode... 62 3b 7b 7d 00 9b 9a e8 ad 7f 3e 77 34 73 f3 c0 39 71 d0 42
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Received SHSH blobs
Extracting iBEC.d64.RELEASE.im4p (Firmware/dfu/iBEC.d64.RELEASE.im4p)...
Personalizing IMG4 component iBEC...
Sending iBEC (986045 bytes)...
Recovery Mode Environment:
iBoot build-version=iBoot-8419.0.79.0.2
iBoot build-style=RELEASE
Sending RestoreLogo...
Extracting applelogo@2778~iphone.im4p (Firmware/all_flash/applelogo@2778~iphone.im4p)...
Personalizing IMG4 component RestoreLogo...
Sending RestoreLogo (29366 bytes)...
Extracting h14_ane_fw_bia_d6x.im4p (Firmware/ane/h14_ane_fw_bia_d6x.im4p)...
Personalizing IMG4 component ANE...
Sending ANE (5043819 bytes)...
Extracting aopfw-iphone14aop.im4p (Firmware/AOP/aopfw-iphone14aop.im4p)...
Personalizing IMG4 component AOP...
Sending AOP (2492379 bytes)...
Extracting AppleAVE2FW_H14.im4p (Firmware/ave/AppleAVE2FW_H14.im4p)...
Personalizing IMG4 component AVE...
Sending AVE (1354115 bytes)...
Extracting armfw_g14p.im4p (Firmware/agx/armfw_g14p.im4p)...
Personalizing IMG4 component GFX...
Sending GFX (1761211 bytes)...
Extracting adc-kratos-d6x.im4p (Firmware/isp_bni/adc-kratos-d6x.im4p)...
Personalizing IMG4 component ISP...
Sending ISP (24697710 bytes)...
Extracting D64_MtpFirmware.im4p (Firmware/D64_MtpFirmware.im4p)...
Personalizing IMG4 component MtpFirmware...
Sending MtpFirmware (3213154 bytes)...
Extracting t8110pmp.im4p (Firmware/pmp/t8110pmp.im4p)...
Personalizing IMG4 component PMP...
Sending PMP (530395 bytes)...
Extracting rans.t8110.release.im4p (Firmware/rans.t8110.release.im4p)...
Personalizing IMG4 component RestoreANS...
Sending RestoreANS (989720 bytes)...
Extracting iphone14d6xdcp.im4p (Firmware/dcp/iphone14d6xdcp.im4p)...
Personalizing IMG4 component RestoreDCP...
Sending RestoreDCP (4597723 bytes)...
Extracting 078-13514-089.dmg.trustcache (Firmware/078-13514-089.dmg.trustcache)...
Personalizing IMG4 component RestoreTrustCache...
Sending RestoreTrustCache (16054 bytes)...
Extracting SmartIOFirmware_ASCv5.im4p (Firmware/SmartIOFirmware_ASCv5.im4p)...
Personalizing IMG4 component SIO...
Sending SIO (1163471 bytes)...
Extracting WirelessPower.iphone14.im4p (Firmware/WirelessPower/WirelessPower.iphone14.im4p)...
Personalizing IMG4 component WCHFirmwareUpdater...
Sending WCHFirmwareUpdater (202397 bytes)...
Extracting iBootData.d64.RELEASE.im4p (Firmware/all_flash/iBootData.d64.RELEASE.im4p)...
Personalizing IMG4 component iBootData...
Sending iBootData (10439 bytes)...
ramdisk-size=0x20000000
Extracting 078-13514-089.dmg (078-13514-089.dmg)...
Personalizing IMG4 component RestoreRamDisk...
Sending RestoreRamDisk (148913118 bytes)...
Extracting DeviceTree.d64ap.im4p (Firmware/all_flash/DeviceTree.d64ap.im4p)...
Personalizing IMG4 component RestoreDeviceTree...
Sending RestoreDeviceTree (56869 bytes)...
Extracting sep-firmware.d64.RELEASE.im4p (Firmware/all_flash/sep-firmware.d64.RELEASE.im4p)...
Personalizing IMG4 component RestoreSEP...
Sending RestoreSEP (6271194 bytes)...
Extracting kernelcache.release.iphone14 (kernelcache.release.iphone14)...
Personalizing IMG4 component RestoreKernelCache...
Sending RestoreKernelCache (20680534 bytes)...
Waiting for device to enter restore mode...
About to restore device...
Connecting now...
Connected to com.apple.mobile.restored, version 15
Device 00008110-001249D83C3B801E has successfully entered restore mode
Hardware Information:
BoardID: 14
ChipID: 33040
UniqueChipID: 5147742653087774
ProductionMode: true
Starting FDR listener thread
Checkpoint 1621 complete with code 0
Checkpoint 1540 complete with code 0
Checkpoint 1679 complete with code 0
Checkpoint 1544 complete with code 0
About to send RootTicket...
Sending RootTicket now...
Done sending RootTicket
Checkpoint 1547 complete with code 0
Waiting for NAND (28)
Checkpoint 1549 complete with code 0
Updating NAND Firmware (58)
Checkpoint 1550 complete with code 0
Checkpoint 1551 complete with code 0
Checkpoint 1628 complete with code 0
Checkpoint 1552 complete with code 0
Checkpoint 1555 complete with code 0
Checkpoint 1662 complete with code 0
About to send NORData...
Found firmware path Firmware/all_flash
Getting firmware manifest from build identity
Extracting LLB.d64.RELEASE.im4p (Firmware/all_flash/LLB.d64.RELEASE.im4p)...
Personalizing IMG4 component LLB...
Extracting ansf.t8110.release.im4p (Firmware/ansf.t8110.release.im4p)...
Personalizing IMG4 component ANS...
Extracting applelogo@2778~iphone.im4p (Firmware/all_flash/applelogo@2778~iphone.im4p)...
Personalizing IMG4 component AppleLogo...
Extracting batterycharging0@2778~iphone.im4p (Firmware/all_flash/batterycharging0@2778~iphone.im4p)...
Personalizing IMG4 component BatteryCharging0...
Extracting batterycharging1@2778~iphone.im4p (Firmware/all_flash/batterycharging1@2778~iphone.im4p)...
Personalizing IMG4 component BatteryCharging1...
Extracting batteryfull@2778~iphone.im4p (Firmware/all_flash/batteryfull@2778~iphone.im4p)...
Personalizing IMG4 component BatteryFull...
Extracting batterylow0@2778~iphone.im4p (Firmware/all_flash/batterylow0@2778~iphone.im4p)...
Personalizing IMG4 component BatteryLow0...
Extracting batterylow1@2778~iphone.im4p (Firmware/all_flash/batterylow1@2778~iphone.im4p)...
Personalizing IMG4 component BatteryLow1...
Extracting glyphplugin@2778~iphone-lightning.im4p (Firmware/all_flash/glyphplugin@2778~iphone-lightning.im4p)...
Personalizing IMG4 component BatteryPlugin...
Extracting DeviceTree.d64ap.im4p (Firmware/all_flash/DeviceTree.d64ap.im4p)...
Personalizing IMG4 component DeviceTree...
Extracting liquiddetect@2778~iphone-lightning.im4p (Firmware/all_flash/liquiddetect@2778~iphone-lightning.im4p)...
Personalizing IMG4 component Liquid...
Extracting lowpowermode@2778~iphone-lightning.im4p (Firmware/all_flash/lowpowermode@2778~iphone-lightning.im4p)...
Personalizing IMG4 component LowPowerWallet0...
Extracting lowpowerfindmymode@2778~iphone-lightning.im4p (Firmware/all_flash/lowpowerfindmymode@2778~iphone-lightning.im4p)...
Personalizing IMG4 component LowPowerWallet1...
Extracting recoverymode@2778~iphone-lightning.im4p (Firmware/all_flash/recoverymode@2778~iphone-lightning.im4p)...
Personalizing IMG4 component RecoveryMode...
Extracting WirelessPower.iphone14.im4p (Firmware/WirelessPower/WirelessPower.iphone14.im4p)...
Personalizing IMG4 component WCHFirmwareUpdater...
Extracting iBoot.d64.RELEASE.im4p (Firmware/all_flash/iBoot.d64.RELEASE.im4p)...
Personalizing IMG4 component iBoot...
Extracting sep-firmware.d64.RELEASE.im4p (Firmware/all_flash/sep-firmware.d64.RELEASE.im4p)...
Personalizing IMG4 component RestoreSEP...
Extracting sep-firmware.d64.RELEASE.im4p (Firmware/all_flash/sep-firmware.d64.RELEASE.im4p)...
Personalizing IMG4 component SEP...
Sending NORData now...
Done sending NORData
Checkpoint 1545 complete with code 0
Checkpoint 1683 complete with code 0
Unmounting filesystems (29)
Unmounting filesystems (29)
Unmounting filesystems (29)
Unmounting filesystems (29)
Unmounting filesystems (29)
Unmounting filesystems (29)
Checking filesystems (15)
Checkpoint 1637 complete with code 0
Checkpoint 1556 complete with code 0
Checkpoint 1686 complete with code 0
About to send BuildIdentity Dict...
common.c:printing 0 bytes plist:
(null)Sending BuildIdentityDict now...
Done sending BuildIdentityDict
Checkpoint 1699 complete with code 0
Checkpoint 1695 complete with code 0
Checkpoint 1620 complete with code 0
Checkpoint 1687 complete with code 0
Checkpoint 1557 complete with code 0
About to send FDR Trust data...
Sending FDR Trust data now...
Done sending FDR Trust Data
Checkpoint 1558 complete with code 0
Checkpoint 1559 complete with code 0
Checkpoint 1560 complete with code 0
Checking for uncollected logs (44)
Checkpoint 1561 complete with code 0
Checking for uncollected logs (44)
Checkpoint 1562 complete with code 0
ERROR: Unable to receive message from FDR 0x7fb51e52b380 (-2). 0/2 bytes
Checkpoint 1563 complete with code 0
Checkpoint 1633 complete with code 0
Unmounting filesystems (29)
Unmounting filesystems (29)
Unmounting filesystems (29)
Unmounting filesystems (29)
Unmounting filesystems (29)
Unmounting filesystems (29)
Checkpoint 1565 complete with code 0
Checkpoint 1614 complete with code 0
Checkpoint 1567 complete with code 0
Checkpoint 1674 complete with code 0
Checkpoint 1632 complete with code 0
Checkpoint 1570 complete with code 0
Checkpoint 1629 complete with code 0
Checkpoint 5645 complete with code 0
Creating filesystem (12)
Checkpoint 1624 complete with code 0
Checkpoint 1625 complete with code 0
Checkpoint 1626 complete with code 0
About to send filesystem...
Connected to ASR
Validating the filesystem
Filesystem validated
Sending filesystem now...
[==================================================] 100.0%
Done sending filesystem
Verifying restore (14)
[==================================================] 100.0%
Checkpoint 1627 complete with code 0
Checkpoint 1664 complete with code 0
Checkpoint 1653 complete with code 0
Checkpoint 1676 complete with code 0
Unmounting filesystems (29)
Unmounting filesystems (29)
Unmounting filesystems (29)
Unmounting filesystems (29)
Unmounting filesystems (29)
Unmounting filesystems (29)
Checking filesystems (15)
Checking filesystems (15)
Checking filesystems (15)
Checking filesystems (15)
Checking filesystems (15)
Checking filesystems (15)
Mounting filesystems (16)
Mounting filesystems (16)
Mounting filesystems (16)
Mounting filesystems (16)
Checkpoint 1574 complete with code 0
Checkpoint 1634 complete with code 0
Checkpoint 1655 complete with code 0
Checkpoint 1658 complete with code 0
Checkpoint 4294968871 complete with code 0
Checkpoint 4294968986 complete with code 0
Checkpoint 4294968987 complete with code 0
Checkpoint 1618 complete with code 0
About to send BuildIdentity Dict...
common.c:printing 0 bytes plist:
(null)Sending BuildIdentityDict now...
Done sending BuildIdentityDict
About to send BuildIdentity Dict...
common.c:printing 0 bytes plist:
(null)Sending BuildIdentityDict now...
Done sending BuildIdentityDict
Sending Cryptex1 TSS request...
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Received Cryptex1,Ticket
Sending FirmwareResponse data now...
Done sending FirmwareUpdater data
About to send BuildIdentity Dict...
common.c:printing 0 bytes plist:
(null)Sending BuildIdentityDict now...
Done sending BuildIdentityDict
ERROR: restore_send_firmware_updater_data: Got unknown updater name 'Cryptex1LocalPolicy'.
ERROR: Unable to send FirmwareUpdater data
ERROR: Unable to successfully restore device
ERROR: Unable to restore device
```

**Comment by Lethaltail** [comment]
Should now be working with #507.

**Comment by Lethaltail** [comment]
Fixes are still looking good on Beta 3!

**Comment by nikias** [comment]
Thanks for confirming!

**Comment by sitay1** [comment]
The fixes you guys did seems to fix that issue. Thanks. Closing it.

**Comment by WilsontheWolf** [comment]
I am having a similar issue, restoring the 16.0 Beta 3 Update. https://haste.antti.codes/iyihomofup.yaml

**Comment by WilsontheWolf** [comment]
Ok so I reverted back to commit eff9fab and it worked, so there appears to be a regression somewhere
