### ISSUE TITLE
undefined reference to `plist_from_json'

### ISSUE THREAD

**Issue by Aquarian-Age** [libimobiledevice/idevicerestore#523]
Compiling according to the latest source code will prompt
undefined reference to `plist_from_json'

- grep "plist_from_json" /usr/local/include/plist/ -nr
```bash
/usr/local/include/plist/plist.h:728: plist_err_t plist_from_json(const char *json, uint32_t length, plist_t * plist);
````
The following method still throws an error
```bash
./autogen.sh --includedir=/usr/local/include/plist/
or
./autogen.sh --includedir=/usr/local/include/
````

- [config.log](https://github.com/libimobiledevice/idevicerestore/files/9467203/config.log)

**Comment by nikias** [comment]
Apparently it is linking against an older binary version of libplist. Check if you have an older version installed.
