### ISSUE TITLE
libimobiledevice-glue-1.0.so.0 no such file or dir

### ISSUE THREAD

**Issue by jenn-arai** [libimobiledevice/idevicerestore#537]
i get:

```idevicerestore: error while loading shared libraries: libimobiledevice-glue-1.0.so.0: cannot open shared object file: No such file or directory```

when i try : 

idevicerestore --erase --latest

ive no idea what to do

**Comment by jenn-arai** [comment]
okay its okay ```ldconfig``` fixed it

**Comment by erzakiev** [comment]
@jenn-arai tnx!! it worked! But what's the mechanism behind this magic tho?
