### ISSUE TITLE
MacOS 13 RestoreDCP Error

### ISSUE THREAD

**Issue by kuper0201** [libimobiledevice/idevicerestore#547]
The latest master branch is being built and used.
Restore to MacOS Monterey(12) works fine, but restore to MacOS Ventura(13) does not work.
I think The restore process seems to have changed in MacOS Ventura.

I will attach the error log.

![스크린샷 2022-10-25 오후 11 20 22](https://user-images.githubusercontent.com/17348056/197911700-f1100a0e-e8a8-4e9c-81c7-1d41735b5a04.png)

**Comment by kuper0201** [comment]
I am using M1 Mac Book Pro 2020.

**Comment by nikias** [comment]
It looks like the device disconnects, the `Unable to set device configuration` is an indicator of that... no idea what exactly is wrong yet. That being said, restore for iOS/iPad OS 16.1 is also broken...

**Comment by kuper0201** [comment]
The apple Configurator 2 also does not work. I think it's Apple's problem.

**Comment by cheesycod** [comment]
I can reproduce this issue as well on Macbook Air 2020
