### ISSUE TITLE
Smarter shopping, Better living!
Check out this item or explore more on AliExpress!
https://campaign.aliexpress.com/wow/gcp/ranking/index?wh_weex=true&_immersiveMode=true&wx_navbar_hidden=true&wx_navbar_transparent=true&ignoreNavigationBar=true&wx_statusbar_hidden=true&preDownLoad=true&rankId=15431015&rankCategoryId=13&labelId=10322064&leafCateId=14191104&rankType=TOP_IDEAL_2020&tagId=manual_global_label_655147259904462940_14191104&requestFrom=other&productIds2Top=1005001798369404&scm=1007.30282.289612.0&scm_id=1007.30282.289612.0&scm-url=1007.30282.289612.0&pvid=19573c6b-0eb3-4b77-b75f-e7764e0aa3c4&floorId=6600008&spm=a1z65.home.rankings.item0&wh_prefetch=gzc0kpo0zt11el84

### ISSUE THREAD

**Issue by hkokarma** [libimobiledevice/idevicerestore#557]
Smarter shopping, Better living!
Check out this item or explore more on AliExpress!
https://campaign.aliexpress.com/wow/gcp/ranking/index?wh_weex=true&_immersiveMode=true&wx_navbar_hidden=true&wx_navbar_transparent=true&ignoreNavigationBar=true&wx_statusbar_hidden=true&preDownLoad=true&rankId=15431015&rankCategoryId=13&labelId=10322064&leafCateId=14191104&rankType=TOP_IDEAL_2020&tagId=manual_global_label_655147259904462940_14191104&requestFrom=other&productIds2Top=1005001798369404&scm=1007.30282.289612.0&scm_id=1007.30282.289612.0&scm-url=1007.30282.289612.0&pvid=19573c6b-0eb3-4b77-b75f-e7764e0aa3c4&floorId=6600008&spm=a1z65.home.rankings.item0&wh_prefetch=gzc0kpo0zt11el84

**Comment by OldWorldOrdr** [comment]
lmao ive never seen a spam github issue before

**Comment by nikias** [comment]
Same 🤣
