### ISSUE TITLE
RESTORE LOCKED IPHONE 6?

### ISSUE THREAD

**Issue by sant1mate** [libimobiledevice/idevicerestore#570]
Salut :)
I was wondering how to restore an iPhone 6 that my cousin gifted me, by using libimobiledevice on Windows 10.
The problem is that this iPhone has an iCloud account so I can't restore it by settings or codes that are sent to an email because he does not remember his Apple ID's password and his email too. I don't blame him because he got this iPhone when it came out for the first time, so, it's been a long time to remember his data.
Dear Github's community, PLEASE HELP ME. 
How can I restore my iPhone by using libimobiledevice and what codes do I need? What's the procedure on Windows?
I want to hear from you.
Best regards.

**Comment by nikias** [comment]
The problem is not the restore process, because that works even if the device is locked, but you can't activate without the iCloud credentials. I can't give you any help here but google is your friend.
