### ISSUE TITLE
libirecovery version requirement is wrong

### ISSUE THREAD

**Issue by marcan** [libimobiledevice/idevicerestore#576]
[This](https://github.com/libimobiledevice/libirecovery/commit/1d20bed9ab853507b013e0ab0fdfa11be393d1e0) commit downgraded the version from 1.0.1, but idevicerestore still wants 1.0.1, so the latest git versions of everything fail to work.

**Comment by nikias** [comment]
I was in the process of merging a few commits and fix some open issues, but then unexpectedly broke a finger last week. I want to tag a release today.

**Comment by nikias** [comment]
https://github.com/libimobiledevice/libirecovery/releases/tag/1.1.0
