### ISSUE TITLE
iPhone 15 in recovery mode fails

### ISSUE THREAD

**Issue by skortela** [libimobiledevice/idevicerestore#599]
Restore with iPhone 15 in recovery mode fails always. It succees if device is in normal mode.
Latest idevicerestore version was used.

[failure.log](https://github.com/libimobiledevice/idevicerestore/files/12800126/failure.log)

**Comment by nikias** [comment]
This issue has been resolved with latest commits.

**Comment by skortela** [comment]
Verified to be working now.
Thanks @nikias!

**Comment by nikias** [comment]
Thanks for confirming!
