### ISSUE TITLE
ERR0R : Device failed to enter restore mode.

### ISSUE THREAD

**Issue by Jiro0262** [libimobiledevice/idevicerestore#605]
Hello,
I try to use idevicerestore with a Macbook Pro 2022 M2 13" and i'm blocked at : 
`ERR0R : Device failed to enter restore mode.`
`Please make sure that usbmuxd is running.`

I already tryied everything from others posts (`sudo usbmuxd`, etc.).
Btw, time between : ``Waiting for device to enter restore mode...`` and  ``irecv_event_cb: device 001071e93421401e (udid: N/A) connected in Recovery mode`` is almost instant.

Feel free to ask me everything like logs, etc.
Thanks !

**Comment by kode54** [comment]
Try running:

```
sudo usbmuxd -f
```

in another terminal, then:

```
sudo idevicerestore <your parameters>
```

Yes, sudo idevicerestore too.

**Comment by Jiro0262** [comment]
Thank you for your reply. I couldn't try since i've restore my device with another mac since.
