### ISSUE TITLE
libirecovery-master Problem with Make on kali

### ISSUE THREAD

**Issue by genhack** [libimobiledevice/idevicerestore#62]
Hello to all i have a problem with make of libirecovery, how i can resolve this problem? thanks in advance

libirecovery-master# make 
make  all-recursive
make[1]: ingresso nella directory "/root/libimobiledevice/libirecovery-master"
Making all in src
make[2]: ingresso nella directory "/root/libimobiledevice/libirecovery-master/src"
make[2]: Nessuna operazione da eseguire per "all".
make[2]: uscita dalla directory "/root/libimobiledevice/libirecovery-master/src"
Making all in include
make[2]: ingresso nella directory "/root/libimobiledevice/libirecovery-master/include"
make[2]: Nessuna operazione da eseguire per "all".
make[2]: uscita dalla directory "/root/libimobiledevice/libirecovery-master/include"
Making all in tools
make[2]: ingresso nella directory "/root/libimobiledevice/libirecovery-master/tools"
  CC       irecovery-irecovery.o
irecovery.c:26:31: fatal error: readline/readline.h: File o directory non esistente
 #include <readline/readline.h>
                               ^
compilation terminated.
Makefile:422: set di istruzioni per l'obiettivo "irecovery-irecovery.o" non riuscito
make[2]: **\* [irecovery-irecovery.o] Errore 1
make[2]: uscita dalla directory "/root/libimobiledevice/libirecovery-master/tools"
Makefile:454: set di istruzioni per l'obiettivo "all-recursive" non riuscito
make[1]: **\* [all-recursive] Errore 1
make[1]: uscita dalla directory "/root/libimobiledevice/libirecovery-master"
Makefile:362: set di istruzioni per l'obiettivo "all" non riuscito
make: **\* [all] Errore 2

**Comment by nikias** [comment]
Install libreadline devel package.
