### ISSUE TITLE
 No firmwares are currently being signed

### ISSUE THREAD

**Issue by coffseducation** [libimobiledevice/idevicerestore#648]
I am attempting to factory reset the OG iphone.
Command give me the following:

`Found device in Recovery mode
Identified device as m68ap, iPhone1,1
ERROR: No firmwares are currently being signed for iPhone1,1 (REALLY?!)`

This phone I think was jailbroken to work in Australia. It may still be. Has this something to do with the print error?

**Comment by nikias** [comment]
I need to merge in a PR that adds support for iOS 1 and 2...

**Comment by coffseducation** [comment]
Ok, so the OG iphone is at present unsupported with idevicerestore ?
Thanks.

**Comment by nikias** [comment]
Correct
