### ISSUE TITLE
ERROR: Unable to restore device

### ISSUE THREAD

**Issue by Poulpoutine** [libimobiledevice/idevicerestore#65]
I have a problem:

[...]

Sending filesystem now...
[==========                                        ]  19.0%ERROR: Unable to send data to ASR. Sent 0 of 20 bytes.
ERROR: Unable to send chunk checksum
ERROR: Unable to send payload to ASR
ERROR: Unable to send filesystem
ERROR: Unable to successfully restore device
Got status message
Status: Fail
Log is available:
 = 0x0 
Scaler 0 enableDeviceClock(false,FULL_CLOCK_INDEX) = 0x0 
void AppleRGBOUT::verify_swap_gated(IOMFBSwapIORequest _, bool *) failed fIsDPOut: 0 fDPDriver: 0 fTVOUTDelegate: 0
AppleRGBOUT verify_swap failed
void AppleRGBOUT::verify_swap_gated(IOMFBSwapIORequest *, bool *) failed fIsDPOut: 0 fDPDriver: 0 fTVOUTDelegate: 0
AppleRGBOUT verify_swap failed
AppleS5L8920XBasebandSPIController::loadConfiguration: NCLK Frequency 48857142, Prescaler 3
BasebandSPIDevice::exitLowPower: Invalid state inactive
AppleSerialMultiplexer: adap::start: Frame size is 2048, Rx Buffer count is 16
AppleSerialMultiplexer: mux::start: created new mux (17) for spi-baseband with adapter BasebandSPIDevice
AppleSerialMultiplexer: debugparams::init: Parsed flags "" ( 0 )
AppleSerialMultiplexer: !! mux::setPowerStateGated: Skipping power state change
AppleSamsungSerial: Identified Serial Port on ARM Device=uart1 at 0x82600000(0x8bf4e000)
AppleSamsungSerial: Identified Serial Port on ARM Device=uart2 at 0x82700000(0x8bf56000)
AppleSamsungSerial: Identified Serial Port on ARM Device=uart3 at 0x82800000(0x8ca26000)
AppleSamsungSerial: Identified Serial Port on ARM Device=uart6 at 0x82b00000(0x8ca28000)
[HPark] AUD10::start: 0x800f6000, highland-park mIISNub: 0x91932080, sampleRate = 44100, ol=10, oi=12
AppleCS42L61Audio: could not allocate control 395
AppleARMBacklight::start: _minDACLevel=456 _maxDACLevel=1971
AppleMultitouchN1SPI: successfully started
AppleRGBOUT: TVOUT device is detected
ApplePinotLCD: _lcdPanelID: 0xa5970dc8 _lcdPanelClass: 2
IOReturn AppleMobileCLCD::set_ditherTable_state(bool), mIsCLCDDitherFor8Bits is true, no dynamic dither table.
[HPark] AUD10::start: 0x800f6000, highland-park mIICNub: 0x8fb5d540, mIISNub: 0x91932080, mSerialNub: 0x918fb400, sampleRate = 44100, ol=10, oi=12
AppleD1815PMUPowerSource: AppleUSBCableDetect 1
AppleD1815PMUPowerSource: AppleUSBCableType USBHost
[HPark] AUD10 ATSc values: [ mic1: 0x00000010, mic2: 0x000000f7, mic3: 0x00000000, recv: 0x00000000, spk: 0x00000000 ]
[HPark] AUD10::setPowerState() function called whereas Start() is not finished
AppleSynopsysOTGDevice::gated_handleUSBCableConnect cable connected, but don't have device configuration yet
AppleSynopsysOTGDevice::gated_handleUSBCableConnect cable connected, but don't have device configuration yet
AppleMultitouchN1SPI: detected HBPP. driver will be kept alive
IOSDIOController::enumerateSlot(): Searching for SDIO device in slot: 0
IOSDIOController::enumerateSlot(): Found SDIO I/O device. Function count(1), memory(0)
IOSDIOIoCardDevice::parseFn0CISTuple(): Device manufacturer ID 0x2d0, Product ID 0x4329
IOSDIOIoCardDevice::parseFn0CISTuple(): Manufacturer: ""
IOSDIOIoCardDevice::parseFn0CISTuple(): Product:      ""
IOSDIOIoCardDevice::parseFn0CISTuple(): ProductInfo0: "s=B1"
IOSDIOIoCardDevice::parseFn0CISTuple(): ProductInfo1: "P=N90 m=3.1 V=m"
AppleBCMWLANBusInterfaceSdio::start(): Started by: IOSDIOIoCardDevice, AppleBCMWLANV2-259 Jun 11 2014 20:13:01
AppleBCMWLANCore::init(): IO80211-46 Jun 11 2014 20:10:01
000060.775046 wlan.N[0] AppleBCMWLANCore::start(): Starting with MAC Address: 5c:59:48:0f:50:44
IO80211Peer::addPhyStatistics Phy stats started for addr 00:be:ef:ff:ff:ff
IO80211Peer::addPhyStatistics Tx Completion stats started for addr 00:be:ef:ff:ff:ff
IO80211PeerManager::initWithInterface cant add monitoring timer
Started logging for intf
IO80211PeerManager::initWithInterface: inited peer manager
IO80211Interface::init peerManager=0x919db000
start:156
start:156
000060.778701 wlan.N[1] AppleBCMWLANCore::setPowerStateGated():   powerState 1, fStateFlags 0x20, dev 0x802fd000 (this 1, provider 0)
000060.778744 wlan.N[2] AppleBCMWLANCore::setPowerStateGated():  Received power state change before driver has initialized, ignoring
AppleSynopsysOTGDevice::gated_handleUSBCableConnect cable connected, but don't have device configuration yet
read new style signature 0x43313131 (line:389)
[FTL:MSG] VSVFL Register  [OK]
[WMR:MSG] Metadata whitening is set in NAND signature
[FTL:MSG] VFL Init            [OK]
display-scale = 2
display-rotation = 0
found applelogo at /usr/share/progressui/applelogo@2x.tga
[FTL:MSG] VFL_Open            [OK]
[FTL:MSG] YAFTL Register  [OK]
found display: primary
display: 640 x 960
found PTP interface
AppleSynopsysOTGDevice - Configuration: PTP
AppleSynopsysOTGDevice          Interface: PTP
AppleSynopsysOTGDevice - Configuration: iPod USB Interface
AppleSynopsysOTGDevice          Interface: USBAudioControl
AppleSynopsysOTGDevice          Interface: USBAudioStreaming
AppleSynopsysOTGDevice          Interface: IapOverUsbHid
AppleSynopsysOTGDevice - Configuration: PTP + Apple Mobile Device
AppleSynopsysOTGDevice          Interface: PTP
AppleSynopsysOTGDevice          Interface: AppleUSBMux
AppleSynopsysOTGDevice - Configuration: PTP + Apple Mobile Device + Apple USB Ethernet
AppleSynopsysOTGDevice          Interface: PTP
AppleSynopsysOTGDevice          Interface: AppleUSBMux
AppleSynopsysOTGDevice          Interface: AppleUSBEthernet
AppleSynopsysOTGDevice::gated_registerFunction Register function USBAudioControl
AppleSynopsysOTGDevice::gated_registerFunction Register function USBAudioStreaming
IOAccessoryPortUSB::start
AppleSynopsysOTGDevice::gated_registerFunction Register function IapOverUsbHid
virtual bool AppleUSBDeviceMux::start(IOService *) build: Jun 11 2014 20:11:28
init_waste
AppleSynopsysOTGDevice::gated_registerFunction Register function AppleUSBMux
AppleSynopsysOTGDevice::gated_registerFunction Register function AppleUSBEthernet
AppleSynopsysOTGDevice::gated_registerFunction Register function PTP
AppleSynopsysOTGDevice::startUSBStack Starting usb stack
IOReturn AppleUSBDeviceMux::setPropertiesGated(OSObject *) setting debug level to 7
[FTL:MSG] FTL_Open            [OK]
[NAND] _publishServices:642 FTL capabilities: 0x00000000
[nand_part_core:INF@ 157] published partition 0
[nand_part_core:INF@ 157] published partition 1
[nand_part_core:INF@ 157] published partition 2
[nand_part_core:INF@ 157] published partition 3
[nand_part_core:INF@ 157] published partition 5
[nand_part_core:INF@ 157] published partition 6
AppleSynopsysOTGDevice::stallBadSetupRequest request: a2 81 0100 0081 0003
AppleSynopsysOTGDevice::stallBadSetupRequest request: 21 0a 0000 0002 0000
AppleSynopsysOTGDevice::stallBadSetupRequest request: a1 01 0101 0002 0006
AppleSynopsysOTGDevice::stallBadSetupRequest request: a1 01 0102 0002 000a
AppleSynopsysOTGDevice::stallBadSetupRequest request: a1 01 0103 0002 000e
AppleSynopsysOTGDevice::stallBadSetupRequest request: a1 01 0104 0002 0012
AppleSynopsysOTGDevice::stallBadSetupRequest request: a1 01 0105 0002 001a
AppleSynopsysOTGDevice::stallBadSetupRequest request: a1 01 0106 0002 0032
AppleSynopsysOTGDevice::stallBadSetupRequest request: a1 01 0107 0002 0060
AppleSynopsysOTGDevice::stallBadSetupRequest request: a1 01 0108 0002 00c2
AppleSynopsysOTGDevice::stallBadSetupRequest request: a1 01 0109 0002 0102
AppleSynopsysOTGDevice::stallBadSetupRequest request: a1 01 010a 0002 0182
AppleSynopsysOTGDevice::stallBadSetupRequest request: a1 01 010b 0002 0202
AppleSynopsysOTGDevice::stallBadSetupRequest request: a1 01 010c 0002 0300
[effaceable:INIT] found current generation, 49, in group 0
[effaceable:INIT] started
[effaceable:INIT] started
AppleUSBDeviceMux::handleConnectResult new session 0x93118630 established 62078<-lo0->49152 62078<-usb->1
void AppleUSBDeviceMux::handleMuxTCPInput(mbuf_t) received reset, closing 0x93118630
AppleARMBacklight::start: No AAP function
AppleUSBDeviceMux::handleConnectResult new session 0x93118630 established 62078<-lo0->49153 62078<-usb->2
void AppleUSBDeviceMux::handleConnectResult(struct BulkUSBMuxSession *, errno_t) new session to port 1082 failed: 61
AppleUSBDeviceMux::handleConnectResult new session 0x93118580 established 62078<-lo0->49155 62078<-usb->4
unrecognized request 'GetValue'
AppleUSBDeviceMux::handleConnectResult new session 0x93118528 established 62078<-lo0->49156 62078<-usb->5
unrecognized request 'GetValue'
AppleUSBDeviceMux::handleConnectResult new session 0x931184d0 established 62078<-lo0->49157 62078<-usb->6
unrecognized request 'GetValue'
void AppleUSBDeviceMux::handleConnectResult(struct BulkUSBMuxSession *, errno_t) new session to port 1082 failed: 61
void AppleUSBDeviceMux::handleConnectResult(struct BulkUSBMuxSession *, errno_t) new session to port 1082 failed: 61
void AppleUSBDeviceMux::handleConnectResult(struct BulkUSBMuxSession *, errno_t) new session to port 1082 failed: 61
void AppleUSBDeviceMux::handleConnectResult(struct BulkUSBMuxSession *, errno_t) new session to port 1082 failed: 61
void AppleUSBDeviceMux::handleConnectResult(struct BulkUSBMuxSession *, errno_t) new session to port 1082 failed: 61
unrecognized request 'GetValue'
AppleUSBDeviceMux::sessionUpcall socket is closed, session 0x93118528 (62078<-lo0->49156 62078<-usb->5)
AppleUSBDeviceMux::sessionUpcall socket is closed, session 0x931184d0 (62078<-lo0->49157 62078<-usb->6)
void AppleUSBDeviceMux::handleConnectResult(struct BulkUSBMuxSession *, errno_t) new session to port 1082 failed: 61
void AppleUSBDeviceMux::handleConnectResult(struct BulkUSBMuxSession *, errno_t) new session to port 1082 failed: 61
void AppleUSBDeviceMux::handleConnectResult(struct BulkUSBMuxSession *, errno_t) new session to port 1082 failed: 61
void AppleUSBDeviceMux::handleConnectResult(struct BulkUSBMuxSession *, errno_t) new session to port 1082 failed: 61
client protocol version 13
*_\* UUID 2628C4C3-EF38-166E-8676-9A3584C8313B ***
Restore options:
    UUID                           => <CFString 0x17543560 [0x393ae0]>{contents = "2628C4C3-EF38-166E-8676-9A3584C8313B"}
    MinimumSystemPartition         => <CFNumber 0x175434b0 [0x393ae0]>{value = +1531, type = kCFNumberSInt64Type}
    SystemPartitionSize            => <CFNumber 0x175430f0 [0x393ae0]>{value = +1531, type = kCFNumberSInt64Type}
    PersonalizedDuringPreflight    => <CFBoolean 0x393e90 [0x393ae0]>{value = true}
    SystemPartitionPadding         => <CFBasicHash 0x17543290 [0x393ae0]>{type = mutable dict, count = 5,
entries =>
    2 : <CFString 0x175435c0 [0x393ae0]>{contents = "128"} = <CFNumber 0x175434e0 [0x393ae0]>{value = +1280, type = kCFNumberSInt64Type}
    3 : <CFString 0x17543510 [0x393ae0]>{contents = "16"} = <CFNumber 0x175432c0 [0x393ae0]>{value = +160, type = kCFNumberSInt64Type}
    4 : <CFString 0x175432d0 [0x393ae0]>{contents = "32"} = <CFNumber 0x17542cd0 [0x393ae0]>{value = +320, type = kCFNumberSInt64Type}
    5 : <CFString 0x17542bc0 [0x393ae0]>{contents = "8"} = <CFNumber 0x17544390 [0x393ae0]>{value = +80, type = kCFNumberSInt64Type}
    8 : <CFString 0x17542bf0 [0x393ae0]>{contents = "64"} = <CFNumber 0x17542bb0 [0x393ae0]>{value = +640, type = kCFNumberSInt64Type}
}

entering load_sep_os
device has no sep
entering partition_nand_device
device supports boot-from-NAND
nand device is already partitioned
entering wait_for_storage_device
Searching for NAND service
Found NAND service: IOFlashStoragePartition
NAND initialized. Waiting for devnode.
entering clear_remap_variable
executing /usr/sbin/nvram
entering format_effaceable_storage
effaceable storage is formatted, clearing it
effaceable storaged cleared
entering ramrod_probe_media
device partitioning scheme is GPT
find_filesystem_partitions: storage=/dev/disk0s1 system=/dev/disk0s1s1 data=/dev/disk0s1s2
executing /sbin/fsck_hfs
volumeType is 0
0000:  0000 0000 0000 0000 0000 0000 0000 0000       |................|
. . .
01f0:  0000 0000 0000 0000 0000 0000 0000 0000       |................|
Offset 1024 length 512:
0000:  0000 0000 0000 0000 0000 0000 0000 0000       |................|
. . .
01f0:  0000 0000 0000 0000 0000 0000 0000 0000       |................|
*\* /dev/rdisk0s1s1
   Executing fsck_hfs (version hfs-277.10.5).
fsck failed on /dev/disk0s1s1
skipping check for restore log due to old host software
entering clean_NAND
NAND format complete
entering ramrod_probe_media
find_filesystem_partitions: storage=/dev/disk0 system= data=
entering format_storage_for_LwVM
entering ramrod_probe_media
device partitioning scheme is GPT
unexpected partition 'LwVM' - skipping
find_filesystem_partitions: storage=/dev/disk0s1 system= data=
entering create_filesystem_partitions
User specified system partition size, skipping firmware extras size.
system partition padding size is: 167772160 bytes
unable to open : No such file or directory
creating 2 partitions
creating encrypted data partition
entering ramrod_probe_media
device partitioning scheme is GPT
find_filesystem_partitions: storage=/dev/disk0s1 system=/dev/disk0s1s1 data=/dev/disk0s1s2
wipe entire partition: 1 (old = 0 new = 1691)
block size for /dev/disk0s1s1: 8192
/sbin/newfs_hfs -s -v System -J -b 8192 -n a=8192,c=8192,e=8192 /dev/disk0s1s1 
executing /sbin/newfs_hfs -s -v System -J -b 8192 -n a=8192,c=8192,e=8192 /dev/disk0s1s1
void AppleUSBDeviceMux::handleMuxTCPInput(mbuf_t) received reset, closing 0x93118580
Initialized /dev/rdisk0s1s1 as a 2 GB case-sensitive HFS Plus volume with a 8192k journal
block size for /dev/disk0s1s2: 8192
/sbin/newfs_hfs -s -v Data -J -P -b 8192 -n a=8192,c=8192,e=8192 /dev/disk0s1s2 
executing /sbin/newfs_hfs -s -v Data -J -P -b 8192 -n a=8192,c=8192,e=8192 /dev/disk0s1s2
AppleUSBDeviceMux::handleConnectResult new session 0x93118420 established 62078<-lo0->49167 62078<-usb->16
unrecognized request 'GetValue'
AppleUSBDeviceMux::handleConnectResult new session 0x931183c8 established 62078<-lo0->49168 62078<-usb->17
unrecognized request 'GetValue'
Initialized /dev/rdisk0s1s2 as a 13 GB case-sensitive HFS Plus volume with a 8192k journal
entering ramrod_probe_media
device partitioning scheme is GPT
find_filesystem_partitions: storage=/dev/disk0s1 system=/dev/disk0s1s1 data=/dev/disk0s1s2
entering mount_filesystems
executing /sbin/fsck_hfs
*\* /dev/rdisk0s1s1
   Executing fsck_hfs (version hfs-277.10.5).
*\* Checking Journaled HFS Plus volume.
*\* Detected a case-sensitive volume.
   The volume name is System
*\* Checking extents overflow file.
*\* Checking catalog file.
*\* Checking multi-linked files.
*\* Checking catalog hierarchy.
*\* Checking extended attributes file.
*\* Checking volume bitmap.
*\* Checking volume information.
*\* Trimming unused blocks.
*\* The volume System appears to be OK.
executing /sbin/mount_hfs
mount_hfs: Could not create property for re-key environment check: No such file or directory
/dev/disk0s1s1 mounted on /mnt1
executing /sbin/fsck_hfs
*\* /dev/rdisk0s1s2
   Executing fsck_hfs (version hfs-277.10.5).
*\* Checking Journaled HFS Plus volume.
*\* Detected a case-sensitive volume.
   The volume name is Data
*\* Checking extents overflow file.
*\* Checking catalog file.
*\* Checking multi-linked files.
*\* Checking catalog hierarchy.
*\* Checking extended attributes file.
*\* Checking volume bitmap.
*\* Checking volume information.
*\* Trimming unused blocks.
*\* The volume Data appears to be OK.
executing /sbin/mount_hfs
mount_hfs: Could not create property for re-key environment check: No such file or directory
/dev/disk0s1s2 mounted on /mnt2
entering resize_system_partition_to_options
User specified system partition size, skipping firmware extras size.
Found SystemPartitionPadding value of 167772160 bytes
Erasing system partition prior to resize operation.
block size for /dev/disk0s1s1: 8192
/sbin/newfs_hfs -s -v System -J -b 8192 -n a=8192,c=8192,e=8192 /dev/disk0s1s1 
executing /sbin/newfs_hfs -s -v System -J -b 8192 -n a=8192,c=8192,e=8192 /dev/disk0s1s1
Initialized /dev/rdisk0s1s1 as a 2 GB case-sensitive HFS Plus volume with a 8192k journal
executing /sbin/fsck_hfs
*\* /dev/rdisk0s1s1
   Executing fsck_hfs (version hfs-277.10.5).
*\* Checking Journaled HFS Plus volume.
*\* Detected a case-sensitive volume.
   The volume name is System
*\* Checking extents overflow file.
*\* Checking catalog file.
*\* Checking multi-linked files.
*\* Checking catalog hierarchy.
*\* Checking extended attributes file.
*\* Checking volume bitmap.
*\* Checking volume information.
*\* Trimming unused blocks.
*\* The volume System appears to be OK.
executing /sbin/mount_hfs
mount_hfs: Could not create property for re-key environment check: No such file or directory
/dev/disk0s1s1 mounted on /mnt1
Trying to resize system partition to 1773142016 bytes aka 1691 MB
entering adjust_partition_preflight
partition:0 requiredSize=216448
no change in size
Successfully resized the system partition
entering maximize_data_partition
entering adjust_partition_preflight
partition:1 requiredSize=2251799813685248
maximizing data partition to 14181990399 bytes
entering adjust_partition_preflight
partition:1 requiredSize=1731200
no change in size
Successfully resized data partition to consume free blocks
The system partition now has a total HFS+ capacity of 1691 MB
entering ramrod_probe_media
device partitioning scheme is GPT
find_filesystem_partitions: storage=/dev/disk0s1 system=/dev/disk0s1s1 data=/dev/disk0s1s2
entering unmount_filesystems
entering ramrod_ticket_update
looking up root ticket hash
device tree ticket-hash: <CFData 0x175490a0 [0x393ae0]>{length = 20, capacity = 20, bytes = 0xfb5459eee0b6b50b60763f43325a6026c03ab71d}
ticket_hash: FB5459EEE0B6B50B60763F43325A6026C03AB71D
received valid ticket (2741 bytes)
entering restore_images
Successfully marked device node /dev/rdisk0s1s1 as static data
executing /usr/sbin/asr -source asr://localhost:12345 -target /dev/disk0s1s1 -erase -noprompt --chunkchecksum --puppetstrings
void AppleUSBDeviceMux::handleConnectResult(struct BulkUSBMuxSession *, errno_t) new session to port 12345 failed: 61
ASR: asr: Unable to disable idle sleep - -536870199
ASR STATUS: start   241.1   multicast-client
ASR: Waiting for connection attempt from server
AppleUSBDeviceMux::handleConnectResult new session 0x931180b0 established 12345<-lo0->49170 12345<-usb->19
ASR STATUS: setup
ASR: Validating target...done
ASR STATUS: metadata
ASR: Validating source...
void AppleUSBDeviceMux::handleMuxTCPInput(mbuf_t) received reset, closing 0x93118420
ASR: done
ASR: Retrieving scan information...done
ASR: Validating sizes...done
ASR STATUS: restore
unrecognized request 'GetValue'
ASR RESTORE PROGRESS: 2%
ASR RESTORE PROGRESS: 4%
void AppleUSBDeviceMux::handleMuxTCPInput(mbuf_t) received reset, closing 0x931183c8
ASR RESTORE PROGRESS: 6%
ASR RESTORE PROGRESS: 8%
ASR RESTORE PROGRESS: 10%
ASR RESTORE PROGRESS: 12%
ASR RESTORE PROGRESS: 14%
ASR RESTORE PROGRESS: 16%
ASR RESTORE PROGRESS: 18%
void AppleUSBDeviceMux::handleMuxTCPInput(mbuf_t) received reset, closing 0x931180b0
ASR: asr: 
ASR: Socket unexpectedly closed while trying to read() offset 0xDBB466C
ASR: __decompressChunk: backing store read at offset 228366682 length 230024 failed with error 5
ASR: asr: 
ASR: __decompressChunk() error: 5
ASR: Failed to read the stream
ASR: : 
ASR: Input/output error
ASR: __decompressChunk: backing store read at offset 227641219 length 235574 failed with error 5
ASR: __decompressChunk: backing store read at offset 226029867 length 244217 failed with error 5
ASR: __decompressChunk: backing store read at offset 226727922 length 210638 failed with error 5
ASR: __decompressChunk() error: 5
ASR: __decompressChunk() error: 5
ASR: __decompressChunk() error: 5
ASR STATUS: fail
ASR: newfs_hfs: MarkExtentUsed::pread(9, 0x27d5a610, 8192, 4096): Invalid argument
ASR: /sbin/newfs_hfs failed with error 256
ASR: Could not restore - Input/output error
ASR STATUS: fail

ERROR: Unable to restore device

Please help me

**Comment by GeoSn0w** [comment]
Your IPSW might be broken or even the data cable.

**Comment by nikias** [comment]
Could also be a problem with large file support. Closing since no info about device, platform, and command line arguments were given.

**Comment by GeoSn0w** [comment]
I've seen the error before on previous versions of idevicerestore, especially the one compiled by quamotion somewhere in ~2015, the issue has been fixed / has stopped appearing upon using an updated version compiled from here. Since the ticket is from 2015, it might be that. The problem used to appear on 5S if I remember well (might have been present on other devices as well).

Conclusion: the pre-compiled binaries are most likely old / outdated and cause problems.

**Comment by JuaneteMii** [comment]
I don’t know if this is relevant, but if anyone is here with the same problem, check the storage on your pc. You should have enough free space for the task you’re performing, otherwise everything will go on ignoring the fact you don’t have the file you need.
