### ISSUE TITLE
updating firmware

### ISSUE THREAD

**Issue by E3lleyyaa** [libimobiledevice/idevicerestore#669]
Hi
After entering to recovery mode , when I tried to make firmware updating with command :
`idevicerestore -u [my_udid] -l`
I'm getting 
```
idevicerestore 1.0.0-203-gf7e24ce
ERROR: Unable to discover device mode. Please make sure a device is attached.
```

**Comment by KovtonyckIlya** [comment]
@Nikias Bassen
