### ISSUE TITLE
LIBUSB_ERROR_ACCESS

### ISSUE THREAD

**Issue by matteyeux** [libimobiledevice/idevicerestore#69]
After compiled libimobildevice, I have this error Ubuntu 14.04 LTS : <br>
opening device 05ac:1227...
irecv_open_with_ecid: can't connect to device: LIBUSB_ERROR_ACCESS

**Comment by nikias** [comment]
@matteyeux have you tried running it as root or assigning different permissions to the usb device file? I am actually using a udev rules file for that. Given that my local user is in the group "plugdev",  the following udev rule does the trick:
```
ACTION=="add", SUBSYSTEM=="usb", ATTR{idVendor}=="05ac", ATTR{idProduct}=="12[28][0-37]", OWNER="root", GROUP="plugdev", MODE="0660"
```

**Comment by nikias** [comment]
libirecovery commit https://github.com/libimobiledevice/libirecovery/commit/b1bc747824c21749d3d09c1aa6b1ce71087cd8cd will make it possible for non-root users to access the usb device.

**Comment by matteyeux** [comment]
Thanks ! 
(sorry for late reply)
