### ISSUE TITLE
Iphone 6s 15.8.3 problem

### ISSUE THREAD

**Issue by Fskadi** [libimobiledevice/idevicerestore#690]
Hello, all works well till half of loading bar 

Mounting filesystems (16)
ERROR: Unable to receive message from FDR 0x79eaac001390 (-4). 0/2 bytes
ERROR: Unable to receive message from FDR 0x79eaac001c70 (-4). 0/2 bytes
ERROR: Unable to receive message from FDR 0x79eaac0012b0 (-4). 0/2 bytes
ERROR: Unable to receive message from FDR 0x79eaac000e30 (-4). 0/2 bytes
ERROR: Unable to receive message from FDR 0x79eaac0011d0 (-4). 0/2 bytes
Unknown operation (80)
Unknown data request 'PersonalizedData' received

this is where it gets bad, what can i do, idevicerestore is downloaded via yay on archlinux, the image is signed

**Comment by Fskadi** [comment]
i recompiled from github, now on version 1.0.0, same thing

**Comment by Fskadi** [comment]
i thought it might need a computer reboot, i did, tried again, same thing happens so i don't think i'm doing something wrong

**Comment by nikias** [comment]
What does `idevicerestore --version` show?

**Comment by Fskadi** [comment]
idevicerestore 1.0.0

**Comment by nikias** [comment]
Yes, then you didn't compile the latest code, or it's using an older build.

**Comment by Fskadi** [comment]
my bad, i forgot to uninstall the yay version, uninstalled everything, git cloned and worked all the way to finish, i have installed ios on my iphone, thank you!!

**Comment by nikias** [comment]
Glad to hear!
