### ISSUE TITLE
ERROR: zip_open while trying to restore iPhone 6S plus

### ISSUE THREAD

**Issue by daniel-bluesea** [libimobiledevice/idevicerestore#71]
i built idevicerestore.exe on mingw.
i used it to successfully restore an iPhone 6S.

but when i tried to restore iPhone 6S plus i got the following errors:

C:\MinGW\bin>idevicerestore.exe "iPhone8,2_9.1_13B143_Restore.ipsw"
NOTE: using cached version data
Found device in Normal mode
Identified device as n66map, iPhone8,2
Extracting BuildManifest from IPSW
ERROR: zip_open: q:\danielsh\mac\iPhone8,2_9.1_13B143_Restore.ipsw: 19
ERROR: zip_open: q:\danielsh\mac\iPhone8,2_9.1_13B143_Restore.ipsw: 19
ERROR: Invalid archive
ERROR: Unable to extract BuildManifest from q:\danielsh\mac\iPhone8,2_9.1_13B143_Restore.ipsw. Firmware file might be corrupt.

btw, when building idevicerestore on mac, i manged to restore iPhone 6S plus, so i dont think the problem is the ipsw file.

**Comment by Charyas** [comment]
I get the same problem, do you solve it？

**Comment by alexsoft1** [comment]
Who will answer this question ?

**Comment by daniel-bluesea** [comment]
i think it is already fixed.. it was an issue of "big" ipsw files in a mingw environment

**Comment by nikias** [comment]
@daniel-bluesea is right, the issue occurs when libzip on mingw isn't built properly with support for large files (> 2GB)

**Comment by timonline** [comment]
@nikias i understand this is old but am facing this issue, see below:

ERROR: zip_open: iPhone_4.0_64bit_10.2_14C92_Restore.ipsw: 11
ERROR: zip_open: iPhone_4.0_64bit_10.2_14C92_Restore.ipsw: 11
ERROR: Invalid archive
[Error] ERROR: Unable to extract BuildManifest from iPhone_4.0_64bit_10.2_14C92_Restore.ipsw. Firmware file might be corrupt.
Done: restoring failed.
Failed with errorcode=-3

Any help?

**Comment by byalex3gs** [comment]
yo tengo el mismo error al querer restaurar un iphone 5s alguna solucion

**Comment by NoDaa** [comment]
Tengo el mismo problema, alguien puede ayudar?
