### ISSUE TITLE
Unable to Install idevicerestore (Mac OS X 10.7.5)

### ISSUE THREAD

**Issue by SA-1** [libimobiledevice/idevicerestore#81]
I need to install idevicerestore on Mac OS X 10.7.5. I tried to install libimobiledevice as guided in following links:
1. http://technotesonthego.blogspot.com/2013/10/install-libimobiledevice-on-mac-os-x.html
2. http://macappstore.org/libimobiledevice/
3. https://www.youtube.com/watch?v=hjDJVAV-4gI
I installed everything like they said & libimobiledevice installed at " /usr/local/cellar/libimobiledevice " but idevicerestore is missing there. Then I try from https://github.com/libimobiledevice/idevicerestore but failed with error : 

checking for libimobiledevice... no

configure: error: Package requirements (libimobiledevice-1.0 >= 1.1.6) were not met:

Package 'libplist' requires 'libxml-2.0 >= 2.7.8' but version of libxml-2.0 is 2.7.3

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables libimobiledevice_CFLAGS
and libimobiledevice_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

Complete log is attached.

Need Urgent Help to install idevicerestore. Thanks
[Libimobiledevice Error.txt](https://github.com/libimobiledevice/idevicerestore/files/88797/Libimobiledevice.Error.txt)

**Comment by yehuda2525** [comment]
+1

**Comment by nikias** [comment]
Build and install libplist and libimobiledevice from source.
