### ISSUE TITLE
 compile idevicerestore without internet

### ISSUE THREAD

**Issue by JyotiNagpal** [libimobiledevice/idevicerestore#85]
Hello, i compile the idevicerestore that perfectely run in my Linux System. But i have a question.Is any way to compile idevicerestore without internet? because when i compile the idevicerestore in terminal then Request URL set to https://gs.apple.com/TSS/controller?action=2 . when i disconnect the internet, do not restore device and  Following error occur:->
WARNING: Unable to find BbSkeyId node
Request URL set to https://gs.apple.com/TSS/controller?action=2
Could not resolve host: gs.apple.com
Sending TSS request attempt 1... Request URL set to https://17.171.36.30/TSS/controller?action=2
Could not resolve host: gs.apple.com
Sending TSS request attempt 2... Request URL set to https://17.151.36.30/TSS/controller?action=2
Could not resolve host: gs.apple.com
Sending TSS request attempt 3... Request URL set to http://gs.apple.com/TSS/controller?action=2
Could not resolve host: gs.apple.com
Sending TSS request attempt 4... Request URL set to http://17.171.36.30/TSS/controller?action=2
Could not resolve host: gs.apple.com
Sending TSS request attempt 5... Request URL set to http://17.151.36.30/TSS/controller?action=2
Could not resolve host: gs.apple.com
Sending TSS request attempt 6... Request URL set to https://gs.apple.com/TSS/controller?action=2
Could not resolve host: gs.apple.com
Sending TSS request attempt 7... Request URL set to https://17.171.36.30/TSS/controller?action=2
Could not resolve host: gs.apple.com
Sending TSS request attempt 8... Request URL set to https://17.151.36.30/TSS/controller?action=2
Could not resolve host: gs.apple.com
Sending TSS request attempt 9... Request URL set to http://gs.apple.com/TSS/controller?action=2
Could not resolve host: gs.apple.com
Sending TSS request attempt 10... Request URL set to http://17.171.36.30/TSS/controller?action=2
Could not resolve host: gs.apple.com
Sending TSS request attempt 11... Request URL set to http://17.151.36.30/TSS/controller?action=2
Could not resolve host: gs.apple.com
Sending TSS request attempt 12... Request URL set to https://gs.apple.com/TSS/controller?action=2
Could not resolve host: gs.apple.com
Sending TSS request attempt 13... Request URL set to https://17.171.36.30/TSS/controller?action=2
Could not resolve host: gs.apple.com
Sending TSS request attempt 14... Request URL set to https://17.151.36.30/TSS/controller?action=2
Could not resolve host: gs.apple.com
ERROR: TSS request failed: Could not resolve host: gs.apple.com (status=-1)
Sending TSS request attempt 15... ERROR: Unable to send TSS request
ERROR: Unable to get SHSH blobs for this device
.So, please help if anyone know about this concept.
Note- I compile the idevicerestore with Firmware (ipsw)
Thanks

**Comment by nikias** [comment]
Since Apple is signing the firmware for each restore it does not work offline.
