### ISSUE TITLE
compile idevicerestore when Multiple ios devices connected

### ISSUE THREAD

**Issue by JyotiNagpal** [libimobiledevice/idevicerestore#86]
![screenshot](https://cloud.githubusercontent.com/assets/17399573/13486217/04b78926-e135-11e5-9a08-11c6ca0a6e32.png)

when multiple devices connected on my System...then i compile the one iphone with its corresponding firmware with using its ecid or uid. 
In a starting....Which device i want to restore that device is processed.................
But after the iphone enter into the recovery mode...then waiting for devices..it access the another device which is connected on my system with its uid. That device which is in proecess  recovery mode that device is not access
when only one device is connected ...then everything is fine.

**Comment by nikias** [comment]
It should work when you select the device by ecid.
