### ISSUE TITLE
Cannot restore iphone 6s to iOS 9.3 in windows

### ISSUE THREAD

**Issue by jackczhang** [libimobiledevice/idevicerestore#89]
I got the error as below

update_baseband: requesting baseband firmware data
update_baseband: calling CFNotificationCenterRemoveEveryObserver
Update[Baseband] error - The operation couldn\U2019t be completed. (RamrodErrorDomain error 3 - update_baseband: host failed to provide baseband data)
Update[Baseband] failed - 0 retries remaining...
0: RamrodErrorDomain/3: update_baseband: host failed to provide baseband data
unable to convert ramrod error 3
restore failed with CFError:
0: AMRestoreErrorDomain/ffffffffffffffff: failed to update device firmware
1: AMRestoreErrorDomain/ffffffffffffffff: ramrod firmware update failed
2: RamrodErrorDomain/3: update_baseband: host failed to provide baseband data
waiting for host to acknowledge final status received...
recv(9, 4) failed: connection closed
unable to read message size: -1
received NULL message from host, expected final status
attempting to dump restore log
writing log file: /mnt1/restore.log
.......
About to send BasebandData...
WARNING: Unable to find BbSkeyId node
Sending Baseband TSS request...
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Received Baseband SHSH blobs
ERROR: could not close and write modified archive: Renaming temporary file failed: No such file or directory
ERROR: Unable to send baseband data
ERROR: Unable to successfully restore device
ERROR: Unable to restore device

Any idea?

**Comment by coolhiro** [comment]
i found this situation and solved.
fseek and ftell is problem.
firmware(iOS9.3 of iphone6s) size is bigger than 2^31.
thus, you can use _fseeki64 and _ftelli64.
convert 32bit functions to 64bit functions in asr.c.

**Comment by jackczhang** [comment]
@coolhiro Thanks for your replay, but after update the file asr.c function fseek and ftell, the problem still exists, any idea?

**Comment by coolhiro** [comment]
sorry, i missed something.

change off_t to uint64_t in asr_send_payload of asr.c.
// default code
//off_t i, length, bytes = 0;
// modified code
uint64_t i, length, bytes = 0;

and change below in asr_handle_oob_data_request of asr.c
// default code
// fseeko(file, oob_offset, SEEK_SET);
// if (fread(oob_data, 1, oob_length, file) != oob_length) {
// modified code
_fseeki64( file, oob_offset, SEEK_SET );
uint64_t read_length;
if ( ( read_length = fread(oob_data, 1, oob_length, file) ) != oob_length ) {

these will help you.

**Comment by jackczhang** [comment]
@coolhiro still got the error, when trace the code, found that
the error occurred at restore.c function restore_sign_bbfw() -> zip_close()
// this will write out the modified zip
	if (zip_close(za) == -1) {
		error("ERROR: could not close and write modified archive: %s\n", zip_strerror(za));
		res = -1;
	} else {
		res = 0;
	}
	za = NULL;
	zs = NULL;

**Comment by coolhiro** [comment]
try to modify below in ipsw_extract_to_file() of ipsw.c
// default code
//off_t i, bytes = 0;
// modified code
uint64_t i, bytes = 0;

i think zip_close() error has occured because of invalid bbfw file extraction.

**Comment by nicolassan** [comment]
I had the same issue, i try to apply the modifications, many thanks  coolhiro !!

**Comment by jackczhang** [comment]
@coolhiro thanks, but still get the same error.
It should not be the issue about 64 bit functions for large file.
I think it should be zlib or libzip compile issue, could you share your libzip-4.dll to me?

**Comment by coolhiro** [comment]
show me your e-mail please.
i will send libzip .lib file and compilable package.

**Comment by jackczhang** [comment]
my email is jack_c_zhang@wistron.com, thanks coolhiro.

**Comment by nicolassan** [comment]
Hi,

Can you please send me The dll too ?

My email : nicolassan@outlook.com

Thanks,
Nicolas

**Comment by jackczhang** [comment]
Libzip compile issue, use CMake instead configure command.

**Comment by walkman4321** [comment]
I have also same problem.So i follow every instruction in above post.Still It can't restore firmware to my Iphone 5s. When i again debug code i found that it cannot write data to ".dmg" file .Please help me to figure out this problem

**Comment by vipinbeni** [comment]
Hi Sir @FunkyM ,
I also having the same problem.So i follow every instruction in above post.Still It can't restore firmware to my Iphone 5s. When i debug code i found that it cannot validate ASR my function fail in below calling in validation. i am working on ubantu 14.4.2 ,32 bit , i change fopen with fopeno64 but still i have issue on below step.

device_error = idevice_connection_receive(asr->connection, buffer, ASR_BUFFER_SIZE, &size);
if (device_error != IDEVICE_E_SUCCESS) {
error("ERROR: Unable to receive data from ASR\n");
free(buffer);
return -1;
}

while (1) {
if (asr_receive(asr, &packet) < 0) {
error("ERROR: Unable to receive validation packet\n");
return -1;
}

dear sir kindly help me as it work fine on ipsw less then 2 gb but fail on ipsw 2.2 gb for 5S ios 10.2

**Comment by nikias** [comment]
@walkman4321 as explained here: https://github.com/libimobiledevice/idevicerestore/issues/18 you need to have a newer version of libzip so it can handle files > 2gb.
